### ISSUE TITLE
Provider should reload page if no fetch is found

### ISSUE THREAD

**Issue by bloodyowl** [phenomic/phenomic#1019]

**Comment by bloodyowl** [comment]
(or actually just use XMLHttpRequest, will be simpler)

**Comment by bherila** [comment]
Or just include a `fetch` polyfill? 

There is one by Github: https://github.com/github/fetch

**Comment by MoOx** [comment]
It's more to handle internal link that are to assets, nothing to do with the presence of "fetch" function :)

**Comment by MoOx** [comment]
We include the polyfill.
