### ISSUE TITLE
styles.css generated by default webpack config not included like bundle.js is

### ISSUE THREAD

**Issue by MoOx** [phenomic/phenomic#1044]
We should decide between:
- stop extracting to styles.css by default
- or, like for bundle.js, provide a prop in Html wrapper so people can just call {props.style} like they do for script.

Alternatively it would be nice to have an option to directly inline styles in html. Maybe prop.link for css url and prop.style for inlined styles?

**Comment by MoOx** [comment]
Problem is, some user might not include a .css file, so this file might not be created. We will have to be careful about that.

**Comment by ball-hayden** [comment]
I'm currently struggling to include extracted styles.

I've defined a custom `Html.js`:

```es6
import React from 'react';
import Head from 'react-helmet';

const Html = (props) => {
  const helmet = Head.renderStatic();
  return (
    <html {...helmet.htmlAttributes.toComponent()}>
      <head>
        <link rel="stylesheet" href="./styles.css" />
      </head>
      <body {...helmet.bodyAttributes.toComponent()}>
        {props.body}
        {props.state}
        {props.script}
      </body>
    </html>
  );
};

export default Html;
```

This works, so long as `styles.css` is known. If I wish to add a `[contenthash]` to the filename, I now can't hard-code the path, so I've no idea how to link to my stylesheet.

Is anyone able to help me out?

**Comment by MoOx** [comment]
You can probably handle this by providing your own webpack.config.js at the root of the project. You can copy/paste/adjust this one https://github.com/phenomic/phenomic/blob/c7bddecaa5cad5783569343f3b0692dddadc80cb/packages/plugin-bundler-webpack/src/webpack.config.js

**Comment by bherila** [comment]
@ball-hayden look how they resolve the css filename here
https://github.com/barbar/vortigern/blob/develop/src/app/containers/Html/index.tsx

Alternatively as @MoOx is suggesting you could just have the CSS file output with a static filename.

Regards,
Ben

**Comment by ball-hayden** [comment]
Apologies for the delayed reply.

Thanks @bherila - I'd realised I could provide my own webpack config, but wasn't sure how to get the CSS paths through to my components. It looks like using the `webpack-manifest-plugin` and passing that through (as is done in https://github.com/barbar/vortigern/blob/28131dc3789b3474148aae52c03fe1d37baf4709/src/server.tsx#L94) might be the way forward.

**Comment by medfreeman** [comment]
@ball-hayden i already did something like this in #1121 . i don't know if it will be included as is, but yeah it seems that it is the way forward.

**Comment by MoOx** [comment]
I am having some hard time with pagination, I will look to that after :)

**Comment by MoOx** [comment]
Will be handled by changes in #1138 (in short: a `<Style/>` will be accessible from Html component)

**Comment by ball-hayden** [comment]
Awesome - I'll give that a go.
Thanks @MoOx
