### ISSUE TITLE
Bunch of website issues

### ISSUE THREAD

**Issue by pascalduez** [phenomic/phenomic#1045]
Hi,

Firefox version `53.0.3` 
The blocks with a gradient background have a layout issue.

![screen shot 2017-06-03 at 09 31 41](https://cloud.githubusercontent.com/assets/335467/26751696/e3918bde-483f-11e7-8280-c82c354f008b.png)

**Comment by bloodyowl** [comment]
damn I always forget that firefox handles relative padding in a weird way. will fix, thanks for reporting !

**Comment by Macxim** [comment]
Same issue on the showcase page:

![screen shot 2017-06-03 at 18 43 20](https://cloud.githubusercontent.com/assets/1909957/26755771/a407dd54-488c-11e7-8746-abb65fa71be4.png)

**Comment by dvcarter** [comment]
add safari to the list
safari version 9.1.2

![screen shot 2017-07-12 at 11 16 44 am](https://user-images.githubusercontent.com/6638939/28125273-1b2b7d7a-66f4-11e7-9d92-aff091d2a32a.png)

**Comment by MoOx** [comment]
@dvcarter thanks for reporting. It's another kind of issues probably related to flexbox this time. Are you running macOS 10.11?

**Comment by dvcarter** [comment]
@MoOx yup.

**Comment by dvcarter** [comment]
are there any plans to use semantic-ui to resolve some of these rending issues?

**Comment by MoOx** [comment]
We don't plan to use anything. The website use react-primitives so kind of raw styling here. What is probably going to happen is that we reimplement the same result with some workaround or others properties...

**Comment by MoOx** [comment]
For those curious about this mess http://www.radiumvinteractive.com/flexbox-percentage-margins-and-paddings/.
I fixed the issues I could find with my machine and VMs. It's ok on latest Safari, Chrome, Firefox and Edge.

If you want to help and have an older version, PRs are always welcome!

**Comment by MoOx** [comment]
@dvcarter fyi I just have fixed the bug on Safari. It's related to this https://github.com/philipwalton/flexbugs#11-min-and-max-size-declarations-are-ignored-when-wrapping-flex-items 
Can you confirm it's now ok for you? Also can you confirm you have Safari 10.0?

**Comment by bloodyowl** [comment]
looking good
