### ISSUE TITLE
Sort Posts collection

### ISSUE THREAD

**Issue by kbariotis** [phenomic/phenomic#1052]
My posts (coming from a Ghost installation) have a `date_published` attribute and I would like to sort them by that:

```markdown
---
title: "Writing ..."
date_published: 2015-12-30T20:21:29.000Z
---
```

I've tried different queries (`sortBy`, `by`, `value`) but didn't have any luck:
```javascript
const HomeContainer = createContainer(Home, (props) => ({
  posts: query({ collection: "posts",  sortBy: "date_published", limit: 5, after: props.params.after }),
}))
```

Is this a bug or something that I didn't get correctly?

Thanks

**Comment by kbariotis** [comment]
Ok I [see now](https://github.com/phenomic/phenomic/blob/master/packages/plugin-collector-files/src/index.js#L35). Phenomic expects to a `date` attribute of type string. 

It would be great if that was customizable.

Thanks

**Comment by MoOx** [comment]
Yeah indeed. I don't like the code you mentioned, it's more a hack. We should be able to sort by any field.

Can you try `by: "date_published", order: "asc"` ? (omit the value, it's for specific values: eg: `by: "tags", value: "css"`)

**Comment by kbariotis** [comment]
@MoOx I tried it and for some reason the `query` function returns an empty list.

**Comment by haywirez** [comment]
Best would be if we could pass a function to the `sortBy` as well. Solves all.

**Comment by MoOx** [comment]
Not an option because this is a blocker for pre-rendering. We have to be able to sort before ordering. Otherwise, pagination problems happen.

**Comment by kbariotis** [comment]
@MoOx do you need a hand on this, cause I would love to help you out.

**Comment by MoOx** [comment]
I won't have time to take a look to this before I go into vacations, so I won't be available before the start of July. So if you want to dig, you should probably try thing in plugin-collector-files and/or in core/src/db. A PR is always welcome. Feel free to ask questions if you don't understand something in the current codebase. @bloodyowl might help you on this if necessary.

**Comment by kbariotis** [comment]
Ok, so I am having some hard time trying to debug the process. First of all, I've created a new project and I am altering Phenomic's source code through `node_modules` which is really hard! Are you using another method for debugging/developing Phenomic?

Now, I came to the conclusion that when the `date` field is set in a post's FrontMatter, Phenomic will generate a filename that includes a date, which is not acceptable.

So, this:
```markdown
---
title: "First blog post"
date: "2015-12-30T20:21:29.000Z"
---
blah blah...
```
will generate a file in path:

`/dist/blog/2015-12-30-first-blog-post.html`

which now alters my previous blog's urls. I've tried adding the `path` property but then Phenomic doesn't sorts posts based on the date.

Now, for the sorting, I haven't really gotten yet how Phenomic's using the level db. I understand that is creating various sublevels with [different keys (sorted and not)](https://github.com/phenomic/phenomic/blob/master/packages/plugin-collector-files/src/index.js#L113) but then I don't understand how those are being generated a) for the `dev` command and b) for the `build` command. 

Any hint that would help me debug easier would be appreciated.

Thanks

**Comment by MoOx** [comment]
# To use/modify Phenomic from git locally, you can

## Play with the docs

Open on terminal in project root (let say ~/phenomic) and one in (~/phenomic/docs).
Then run `npm start` from docs to get the dev server running, and run `npm run transpile` from root everytime you modify a file from packages/*. This will work for development mode. **Note that whenever you modify the server or a plugin you might need to restart the dev server after transpilation.**

## Play with your own project
 
Sort of the same thing must be done, with a local trick for linking phenomic packages.
So clone this repo, run yarn on npm install, then do "npm run link", that should create local links for each packages.
Then in your project, use `npm link @phenomic/core @phenomic/preset-react-app` (and all other direct `@phenomic/*` deps from your package.json.
Then run your code, and don't forget to transpile each time you change phenomic code (+restart dev server if necessary).

It's not optimal so I will try to automate this somehow but it's better than modifying transpiled node_modules

--- 

For the filename thing you should use the key, not the filename. We don't have problem in url for ou news: https://phenomic.io/news/2017/06/introducing-1.0.0-alpha

--- 

For the db, I will admit I am not comfortable with it, @bloodyowl might be able to help us.

**Comment by MoOx** [comment]
Graphql will come so this will help to handle this kind of problem.
