### ISSUE TITLE
Adding custom webpack loaders

### ISSUE THREAD

**Issue by kbariotis** [phenomic/phenomic#1057]
I am opening this generic post while my need is to add the `sass-loader`. I am currently trying to migrate my [Ghost theme](github.com/kbariotis/kostasbariotis.com) into phenomic.

I guess others needs would be possible like adding an image-loader, etc.

**Comment by MoOx** [comment]
This plugin provides a [minimal webpack config](https://github.com/phenomic/phenomic/blob/34055dcec29aae35eb3e624a0c7301a72649d01f/packages/plugin-bundler-webpack/src/webpack.config.js) (to make it easy for newbies), but it should auto read your custom ``webpack.config.js`` at the root of you project. if not, please come here and yell.
Phenomic requirements should be automatically injected (eg: ``process.env.NODE_ENV``).

**Comment by kbariotis** [comment]
@MoOx just an update on this. I didn't manage to make it work, the `webpack.config.js` in my root is not being overridden by the one in the plugin, but instead, Phenomic takes it as is and throws it into webpack.

I did a bit of debugging and saw that when on dev mode (`npm run start`) only the [`getMiddlewares`](https://github.com/phenomic/phenomic/blob/34055dcec29aae35eb3e624a0c7301a72649d01f/packages/plugin-bundler-webpack/src/index.js#L61) function is being called which doesn't do the merging with the default `webpack.config.js`.

Hope that this helps a bit.

**Comment by MoOx** [comment]
user webpack config is not supposed to be merged with plugin-bundler-webpack default one. This one is a minimal/opinionated config.
getWebpackConfig() function is used whenever a config is required so it should work. Just be sure to have an entry for the app.
Does this explanation helps?

**Comment by kbariotis** [comment]
But do I need to add the Phenomic specific configuration, like the `js` loader and the plugins? Should I copy paste the default one `webpack.config.js` and throw my own loaders in it?

**Comment by MoOx** [comment]
You actually need to start from this one indeed! You need to provide a real (full) webpack config.
We are not merging since people might not want babel for example.

**Comment by MoOx** [comment]
And might want "App.js" to be something else etc.

**Comment by mmintel** [comment]
I have the same issue, I copied the webpack.config you mentioned above and added a file loader for images like so:

```
import path from "path";

import webpack from "webpack";
import ExtractTextPlugin from "extract-text-webpack-plugin";

module.exports = (/* config: PhenomicConfig */) => ({
  entry: {
    bundle: [
      process.env.PHENOMIC_ENV !== "static" &&
        require.resolve("webpack-hot-middleware/client"),
      process.env.PHENOMIC_ENV !== "static" &&
        require.resolve("react-hot-loader/patch"),
      "./App.js"
    ].filter(item => item)
  },
  output: {
    publicPath: "/",
    path: path.join(process.cwd(), "dist"),
    filename: "[name].js"
  },
  module: {
    rules: [
      {
        test: /\.(js|jsx)$/,
        exclude: /node_modules/,
        loader: require.resolve("babel-loader"),
        options: {
          babelrc: false,
          presets: [require.resolve("@phenomic/babel-preset")],
          plugins: [require.resolve("react-hot-loader/babel")]
        }
      },
      {
        test: /\.(gif|png|jpe?g|svg)$/i,
        loader: require.resolve('file-loader?hash=sha512&digest=hex&name=[hash].[ext]'),
      },
      {
        test: /\.css$/,
        loader: ExtractTextPlugin.extract({
          fallback: require.resolve("style-loader"),
          use: require.resolve("css-loader")
        })
      }
    ]
  },
  plugins: [
    new ExtractTextPlugin({
      filename: "styles.css",
      disable: process.env.PHENOMIC_ENV !== "static"
    }),
    process.env.PHENOMIC_ENV !== "static" &&
      new webpack.HotModuleReplacementPlugin(),
    process.env.NODE_ENV === "production" &&
      new webpack.optimize.UglifyJsPlugin()
  ].filter(item => item),

  resolve: {
    // react-native(-web) | react-primitives
    extensions: [".web.js", ".js", ".jsx", ".json"],
    alias: {
      "react-native": "react-native-web",

      // to ensure a single module is used
      react: path.resolve(path.join(process.cwd(), "node_modules", "react")),
      "react-dom": path.resolve(
        path.join(process.cwd(), "node_modules", "react-dom")
      ),
      "react-router": path.resolve(
        path.join(process.cwd(), "node_modules", "react-router")
      )
    }
  },

  // eslint-disable-next-line max-len
  // https://github.com/facebookincubator/create-react-app/blob/fbdff9d722d6ce669a090138022c4d3536ae95bb/packages/react-scripts/config/webpack.config.prod.js#L279-L285
  node: {
    fs: "empty",
    net: "empty",
    tls: "empty"
  }
});
```

however I am still getting an error when I try to load a .png file

```
ERROR in ./components/home/avatar.png
Module parse failed: /Users/marcmintel/Projekte/mintel.me/components/home/avatar.png Unexpected character '�' (1:0)
You may need an appropriate loader to handle this file type.
(Source code omitted for this binary file)
 @ ./components/home/index.js 12:14-37
 @ ./App.js
 @ multi (webpack)-hot-middleware/client.js ./~/react-hot-loader/patch.js ./App.js
webpack: Failed to compile.
```

Seems like my config is not applied?

**Comment by kbariotis** [comment]
@mmintel Phenomic will shallow possible errors in your own `webpack.config.js` file and automatically fallback to its own. Can you please double check your config and make sure that contains no errors?

This seems kind weird to me:
```
loader: require.resolve('file-loader?hash=sha512&digest=hex&name=[hash].[ext]'),
```

**Comment by MoOx** [comment]
See https://github.com/phenomic/phenomic/issues/1085#issuecomment-307638675

**Comment by mmintel** [comment]
Thanks! I had to change the import statements to require statements and also change
```
    bundle: [
      process.env.PHENOMIC_ENV !== "static" &&
        require.resolve("webpack-hot-middleware/client"),
      process.env.PHENOMIC_ENV !== "static" &&
        require.resolve("react-hot-loader/patch"),
      "./App.js"
    ].filter(item => item)
```

to 

```
    **"phenomic.main"** : [
      process.env.PHENOMIC_ENV !== "static" &&
        require.resolve("webpack-hot-middleware/client"),
      process.env.PHENOMIC_ENV !== "static" &&
        require.resolve("react-hot-loader/patch"),
      "./App.js"
    ].filter(item => item)
```
