### ISSUE TITLE
Error: ENOENT: ..., lstat on `npm run build` node v. 8 npm v 5

### ISSUE THREAD

**Issue by syndia** [phenomic/phenomic#1059]
```
Error: ENOENT: no such file or directory, lstat '.../Developer/Javascript/syndia/site-v1/public'

0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node', '/usr/local/bin/npm', 'run', 'build' ]
2 info using npm@5.0.0
3 info using node@v8.0.0
4 verbose run-script [ 'prebuild', 'build', 'postbuild' ]
5 info lifecycle site-v1@1.0.0-alpha.1~prebuild: site-v1@1.0.0-alpha.1
6 silly lifecycle site-v1@1.0.0-alpha.1~prebuild: no script for prebuild, continuing
7 info lifecycle site-v1@1.0.0-alpha.1~build: site-v1@1.0.0-alpha.1
8 verbose lifecycle site-v1@1.0.0-alpha.1~build: unsafe-perm in lifecycle true
9 verbose lifecycle site-v1@1.0.0-alpha.1~build: PATH: /usr/local/lib/node_modules/npm/bin/node-gyp-bin:/.../Desktop/Developer/Javascript/syndia/site-v1/node_modules/.bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin
10 verbose lifecycle site-v1@1.0.0-alpha.1~build: CWD: /...Desktop/Developer/Javascript/syndia/site-v1
11 silly lifecycle site-v1@1.0.0-alpha.1~build: Args: [ '-c', 'phenomic build' ]
12 silly lifecycle site-v1@1.0.0-alpha.1~build: Returned: code: 1  signal: null
13 info lifecycle site-v1@1.0.0-alpha.1~build: Failed to exec build script
14 verbose stack Error: site-v1@1.0.0-alpha.1 build: `phenomic build`
14 verbose stack Exit status 1
14 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/lifecycle.js:283:16)
14 verbose stack     at emitTwo (events.js:125:13)
14 verbose stack     at EventEmitter.emit (events.js:213:7)
14 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/spawn.js:40:14)
14 verbose stack     at emitTwo (events.js:125:13)
14 verbose stack     at ChildProcess.emit (events.js:213:7)
14 verbose stack     at maybeClose (internal/child_process.js:887:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:208:5)
15 verbose pkgid site-v1@1.0.0-alpha.1
16 verbose cwd /.../Desktop/Developer/Javascript/syndia/site-v1
17 verbose Darwin 16.5.0
18 verbose argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "build"
19 verbose node v8.0.0
20 verbose npm  v5.0.0
21 error code ELIFECYCLE
22 error errno 1
23 error site-v1@1.0.0-alpha.1 build: `phenomic build`
23 error Exit status 1
24 error Failed at the site-v1@1.0.0-alpha.1 build script.
24 error This is probably not a problem with npm. There is likely additional logging output above.
25 verbose exit [ 1, true ]
```

**Comment by thangngoc89** [comment]
You need to create folder public . YOu can track this issue for a fix https://github.com/phenomic/phenomic/issues/1056

**Comment by MoOx** [comment]
Can you confirm that just creating a public folder fix the proble?

**Comment by syndia** [comment]
ok, created a public folder, now I get another Error:

`Error: EPERM: operation not permitted, unlink '/.../Desktop/Developer/Javascript/syndia/site-v1/dist'`
Looks like a permission error

0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node', '/usr/local/bin/npm', 'run', 'build' ]
2 info using npm@5.0.0
3 info using node@v8.0.0
4 verbose run-script [ 'prebuild', 'build', 'postbuild' ]
5 info lifecycle site-v1@1.0.0-alpha.1~prebuild: site-v1@1.0.0-alpha.1
6 silly lifecycle site-v1@1.0.0-alpha.1~prebuild: no script for prebuild, continuing
7 info lifecycle site-v1@1.0.0-alpha.1~build: site-v1@1.0.0-alpha.1
8 verbose lifecycle site-v1@1.0.0-alpha.1~build: unsafe-perm in lifecycle true
9 verbose lifecycle site-v1@1.0.0-alpha.1~build: PATH: /usr/local/lib/node_modules/npm/bin/node-gyp-bin:/.../Desktop/Developer/Javascript/syndia/site-v1/node_modules/.bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin
10 verbose lifecycle site-v1@1.0.0-alpha.1~build: CWD: /.../Desktop/Developer/Javascript/syndia/site-v1
11 silly lifecycle site-v1@1.0.0-alpha.1~build: Args: [ '-c', 'phenomic build' ]
12 silly lifecycle site-v1@1.0.0-alpha.1~build: Returned: code: 1  signal: null
13 info lifecycle site-v1@1.0.0-alpha.1~build: Failed to exec build script
14 verbose stack Error: site-v1@1.0.0-alpha.1 build: `phenomic build`
14 verbose stack Exit status 1
14 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/lifecycle.js:283:16)
14 verbose stack     at emitTwo (events.js:125:13)
14 verbose stack     at EventEmitter.emit (events.js:213:7)
14 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/spawn.js:40:14)
14 verbose stack     at emitTwo (events.js:125:13)
14 verbose stack     at ChildProcess.emit (events.js:213:7)
14 verbose stack     at maybeClose (internal/child_process.js:887:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:208:5)
15 verbose pkgid site-v1@1.0.0-alpha.1
16 verbose cwd /.../Desktop/Developer/Javascript/syndia/site-v1
17 verbose Darwin 16.5.0
18 verbose argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "build"
19 verbose node v8.0.0
20 verbose npm  v5.0.0
21 error code ELIFECYCLE
22 error errno 1
23 error site-v1@1.0.0-alpha.1 build: `phenomic build`
23 error Exit status 1
24 error Failed at the site-v1@1.0.0-alpha.1 build script.
24 error This is probably not a problem with npm. There is likely additional logging output above.
25 verbose exit [ 1, true ]
