### ISSUE TITLE
Allow configuring port for local server

### ISSUE THREAD

**Issue by neelabhg** [phenomic/phenomic#1063]
Currently, the local server is started at http://localhost:3333.
It is sometimes useful to use another port, such as port [8080 when using Cloud9](https://docs.c9.io/docs/run-an-application).

**Comment by MoOx** [comment]
We have already configuration support (file or package.json), should be easy to add.

**Comment by neelabhg** [comment]
Seems like this is already supported. All I needed to do was add the port to my `package.json`:
```json
"phenomic": {
  "presets": [
    "@phenomic/preset-react-app"
  ],
  "port": 8080
},
```

**Comment by neelabhg** [comment]
Relevant code: https://github.com/phenomic/phenomic/blob/master/packages/core/src/index.js#L12

**Comment by MoOx** [comment]
lol.
So it needs to be documented somewhere.

**Comment by MoOx** [comment]
Will be part of docs
