### ISSUE TITLE
Pagination -> Netlify not working

### ISSUE THREAD

**Issue by syndia** [phenomic/phenomic#1065]
Pagination (Getting Started step 5) is not working in external deploy(Netlify).
Locally everything is ok.

Netlify Link: https://5936b25d3c1d5e343db54c1a--copy-writer-eagle-43323.netlify.com

Browser console message:
Failed to load resource: the server responded with a status of 404 (HTTP/2.0 ...)
https://5936b25d3c1d5e343db54c1a--copy-writer-eagle-43323.netlify.com/phenomic/posts/by-default/1/desc/limit-5/after-cG9zdC00.json

Locally the files are created.

**Comment by syndia** [comment]
Found something more details, it gives an error in there an son file, see image...

<img width="547" alt="schermafbeelding 2017-06-09 om 09 13 19" src="https://user-images.githubusercontent.com/1820680/26965008-426f7bbc-4cf4-11e7-9ae9-f29b33e1582c.png">

**Comment by MoOx** [comment]
Should have been fixed in recent release, let me know if you still have issues.
