### ISSUE TITLE
Error Page not showing on Netlify.com

### ISSUE THREAD

**Issue by syndia** [phenomic/phenomic#1067]
If deployed on Netlify.com, `Getting Started`-step 9 (Error Page) is not showing, it will pick their Error Page.

**Comment by hugmanrique** [comment]
You need to push a `404.html` file into your static dir root in order for Netlify to know where to redirect unknown URL requests (taken from their [docs](https://www.netlify.com/docs/redirects/#custom-404))

**Comment by MoOx** [comment]
Thanks for the info @hugmanrique
