### ISSUE TITLE
Support es2015+ in webpack config

### ISSUE THREAD

**Issue by MoOx** [phenomic/phenomic#1071]
babel-register might help before importing the user config.

https://twitter.com/rstacruz/status/872360854569832450

**Comment by bherila** [comment]
How would this work? It doesn't seem that just installing babel-register magically fixes it, nor does Phenomic pick up/enable babel support on webpack.config.babel.js

**Comment by MoOx** [comment]
Oh ! we dont provide a babel config. Meanwhile you should provide yours.

**Comment by MoOx** [comment]
Should works now, we provide babel-preset-env as a default!
