### ISSUE TITLE
Unlimited requests/fetching if key is not found...

### ISSUE THREAD

**Issue by syndia** [phenomic/phenomic#1073]
If a key is not found, it is sending unlimited requests for fetching data, see image included.

<img width="520" alt="schermafbeelding 2017-06-07 om 21 07 03" src="https://user-images.githubusercontent.com/1820680/26896597-a4202170-4bc5-11e7-904a-793536ac932b.png">

**Comment by MoOx** [comment]
Hum weird. Looks like a bug. Will have a look. Thanks for reporting!

**Comment by MoOx** [comment]
Can you provide more information on how you make your query? Thanks!
