### ISSUE TITLE
Feature: search collection with array values

### ISSUE THREAD

**Issue by syndia** [phenomic/phenomic#1075]
Copy from chat:

> Search a collection with arrays? like I have array of tags `['cs', 'cx'] and I get all articles with exactly this tags in it? if I try value: [array] I don't get any results

**Comment by MoOx** [comment]
@bloodyowl what is the effort on this?

**Comment by bloodyowl** [comment]
it's doable if we sort the query array before sending the request.

**Comment by bloodyowl** [comment]
@syndia are the queries fixed (no dynamic variable as tag) ?

**Comment by syndia** [comment]
@bloodyowl no, but I don't get any error message any more. It returns an empty array

Below the query I'm using:

`export default createContainer(HOC(Component), props => ({
  items: query({
    collection: 'articles',
    ...(props.tags ? { by: 'tags', value: props.tags, limit: 4 } : {}),
  }),
}))
`

**Comment by bloodyowl** [comment]
I'm not sure we want to support this, given the fact this would have a big impact on performance (all possible values in an array of unknown length isn't the kind of algorithm that scales for static rendering) .

**Comment by syndia** [comment]
Ok, you are completely right about performance, I will figure out later, if I have an idea I let you know.

**Comment by MoOx** [comment]
Graphql will come so this will help to handle this kind of problem.
