### ISSUE TITLE
CDN publishing needs a way to prepend CDN url fragment in front of bundle.js and related paths

### ISSUE THREAD

**Issue by yoDon** [phenomic/phenomic#1076]
When Phenomic populates the Helmet script and css paths, it hard-codes them to live in the root of the website but many sites will want to place them on a CDN that's separate from the hosting of the html file

**Comment by MoOx** [comment]
We might solve this by accepting a final url for the website, like in v0.x. So scripts and css might be prefixed by this. That should solve your problem?

**Comment by yoDon** [comment]
I don't think a final url specifier is sufficient. The issue is when using a CDN the js and css files have a different URL from the site. For example the site might be http://Foo.com, with the html file being http://Foo.com/index.html while the js and cs are at http://SomeCDN.com/yadayada/phenomic.browser.123423.js and http://SomeCDN.com/yadayada/phenomic.browser.123423.css

**Comment by MoOx** [comment]
I guess it's doable from custom Html component directly, by not using props send by phenomic and defining script/link yourself. Does this look ok for you? I am afraid that introducing a specific option when you can already handle it will add confusion.

**Comment by yoDon** [comment]
My concern is that the user doesn't have a good way to know which css file is the one that needs path mangling. Yes, you could walk the list of entries in the helmet.link array looking for the one that appears to match the pattern of a phenomic css file and mangle just that one, but that feels kind of sketchy.

The body.script object I think may be simpler/safer, but from here I can't tell whether that's guaranteed to just contain a single script tag whose path could then be mangled or whether it potentially has more complex stuff in it.

**Comment by thangngoc89** [comment]
Providing your own Html component should be the way to go. We dont want to have so many config and flags like 0.2x
Btw, if your website generated by Phenomic is fully static, instead of deploying css, js and images to a CDN, why dont you deploy the whole website there? Your website will be blazing fast.

**Comment by yoDon** [comment]
For a variety of tech stack reasons I need to deploy my HTML to the web server, in part because the entire site isn't able to be static, but I still want to make use of a CDN for the css and js

**Comment by MoOx** [comment]
What we can probably do is to send another props to Html compo that have a list of url, no components directly. Will think about that.

**Comment by bloodyowl** [comment]
I guess we'll need to add a default `DefinePlugin` to PhenomicWebpack which would pass automatically everything found in `process.env` so that users could do:

```javascript
<body {...helmet.bodyAttributes.toComponent()}>
  {props.body}
  {props.state}
  {React.cloneElement(props.script, { src: process.env.URL + props.script.props.src })}
</body>
```

Ok for you?

**Comment by yoDon** [comment]
That looks good for the props.script (which I think is browser.js), but I'm not sure it's enough to let us easily/safely do the same with browser.css. Does it make sense to call out browser.css separately from the other css links, so that it can be handled this way (I think currently browser.js is separate from other user-included js files but browser.css is thrown in with other user-included css files, but I might be misreading that)

**Comment by MoOx** [comment]
Will be part of beta 1
