### ISSUE TITLE
Remove hard coded sans-serif from reason bindings

### ISSUE THREAD

**Issue by MoOx** [phenomic/phenomic#1077]
See https://github.com/phenomic/phenomic/blob/d7aa62e1813a8c2240453719344bdfab28f0c414/packages/reason/src/bodyRenderer.re#L22

@bloodyowl I am not confortable enough with Reason to make sure I won't break things. Maybe we could add automated (minimal) test to cover those files?

**Comment by bloodyowl** [comment]
yup, will do
