### ISSUE TITLE
Array of objects on front matter

### ISSUE THREAD

**Issue by PierrickP** [phenomic/phenomic#1079]
I get an incorrect data object with this kind of markdown file

```md
---
title: 'myTitle'
toto:
  - name: 'titi'
    foo: 'foo'
  - name: 'toto'
    bar: 'bar'
---
body
```

Exemple composant:
```js
const Post = ({ hasError, post }) => {
  console.log(post.node)
  /*
    {
      title: 'myTitle',
      toto: [{
        name: 'toto',
        bar: 'bar'
      }, {
        name: 'toto',
        bar: 'bar'
      }]
      body: {}
    }
   */
  return (<div></div>)
}

const BlogPostContainer = createContainer(Post, (props) => ({
  post: query({ collection: 'posts', id: props.params.splat }),
}))
```

On `toto`, there are toto's length times the last element.

I track it down and it look to be in the core package, function `getSublevel`.
Actually, I don't understand how the relation can work (function `getRelations`)

Thanks

**Comment by bloodyowl** [comment]
we didn't yet plan for nested non-primitives values, I'll look into it
