### ISSUE TITLE
Custom webpack config applied to "phenomic start" not "phenomic build"

### ISSUE THREAD

**Issue by jfjessup** [phenomic/phenomic#1080]
I'm a big fan of what you guys are doing with this project. I've found one issue and I'm wondering if it is expected behavior:

I specified a webpack.config.js file in the root directory of the project. It's a copy of the [minimum webpack config](https://github.com/phenomic/phenomic/blob/34055dcec29aae35eb3e624a0c7301a72649d01f/packages/plugin-bundler-webpack/src/webpack.config.js) except I moved App.js into a src directory. The change is highlighted in the code below.

```
module.exports = (config) => ({
  entry: {
    bundle: [
      process.env.PHENOMIC_ENV !== "static" && require.resolve("webpack-hot-middleware/client"),
      process.env.PHENOMIC_ENV !== "static" && require.resolve("react-hot-loader/patch"),
      path.join(config.path, "src", "App.js")
    ].filter(item => item)
  },...
});
```

When I run "phenomic start" it works as expected. However, when I run "phenomic build" it leads to the following behavior:

- The getWebpackConfig in plugin-bundler-webpack returns the correct config (I added a console log statement to print it out):
```
{ entry: { bundle: [ '/Users/jfjessup/a-company-website/website/src/App.js' ] },
  output: 
   { publicPath: '/',
     path: '/Users/jfjessup/a-company-website/website/dist',
     filename: '[name].js' },
  module: { rules: [ [Object], [Object] ] },
  plugins: 
   [ ExtractTextPlugin { filename: 'styles.css', id: 1, options: [Object] },
     UglifyJsPlugin { options: {} } ],
  resolve: 
   { extensions: [ '.js', '.jsx', '.json' ],
     alias: 
      { react: '/Users/jfjessup/a-company--website/website/node_modules/react',
        'react-dom': '/Users/jfjessup/a-company-website/website/node_modules/react-dom',
        'react-router': '/Users/jfjessup/a-company-website/website/node_modules/react-router' } },
  node: { fs: 'empty', net: 'empty', tls: 'empty' } }
```

- But the commands fails with this:
```
EntryModuleNotFoundError: Entry module not found: Error: Can't resolve '/Users/jfjessup/a-company-website/website/App.js' in '/Users/jfjessup/a-company-website/website'
```

It looks like the src directory was dropped from the entry because the minimum webpack config was used to build the project.

**Comment by jfjessup** [comment]
I think the issue may be in the buildForPrerendering method in the plugin-bundler-webpack. The specialConfig values are overwriting the values returned from the getWebpackConfig call. The issue is fixed when I pass the webpackConfig object into the returned webpackPromise.

**Comment by MoOx** [comment]
Thanks for digging! Your are right. Let me try to simplify this method.
