### ISSUE TITLE
page.node.body.slice is not a function

### ISSUE THREAD

**Issue by mmintel** [phenomic/phenomic#1084]
Hi there,

in your "Getting started" guide on step 6 you suggest using `<meta name="description" content={ page.node.body.slice(0, 150) } />` but I think this line is outdated, as page.node.body returns an object and slice doesn't work with object.

What is your suggested way to deal with that? How can I transform content from markdown to string? Do you provide any helper for that?

Cheers
Marc

**Comment by MoOx** [comment]
Indeed, this is outdated. Let me think and get back with an intuitive solution.

**Comment by syndia** [comment]
`<meta name="description" content={ !isLoading && page.node.body.slice(0, 150) } />` or if not works `<meta name="description" content={ page && page.node && page.node.body.slice(0, 150) } />`

**Comment by MoOx** [comment]
body is a JSON tree. I will make an helper to convert it as text so the slice can be used :)

**Comment by syndia** [comment]
Nice then I can use my Truncate component and ReadingTime component 🥇

**Comment by MoOx** [comment]
A `textRenderer` function will be exposed in alpha 6. step 6 of the getting started will be updated accordingly. It will convert react tree or html to raw text :)
