### ISSUE TITLE
Warn the developer when a custom `webpack.config.js` fails

### ISSUE THREAD

**Issue by kbariotis** [phenomic/phenomic#1085]
Phenomic [currently shallows custom `webpack.config.js` errors](https://github.com/phenomic/phenomic/blob/master/packages/plugin-bundler-webpack/src/index.js#L32). Let the develop know when her custom configuration fails.

**Comment by MoOx** [comment]
Please for now use `$ DEBUG=phenomic:plugin:webpack npm start` to debug your config. I will make a change to only shallow when file does not exist (which was what I want in the first place) and also try to understand why "import" keyword does not work ([since we are already using babel-register](https://github.com/phenomic/phenomic/blob/bedb267be34cad9108dd37c7654bf118a6b070c0/packages/cli/index.js#L5) which should enable this)

**Comment by kbariotis** [comment]
Aw awesome, didnt know that! Thanks.

**Comment by MoOx** [comment]
I added that in alpha 3, but alpha 4 will provide errors out of the box!

**Comment by medfreeman** [comment]
Just note that in my setup, `webpack.config.babel.js` works properly with es6 syntax and imports.

**Comment by MoOx** [comment]
Which version pf phenomic?

**Comment by bherila** [comment]
I have 

```
{
  "private": true,
  "devDependencies": {
    "@phenomic/cli": "^1.0.0",
    "@phenomic/core": "^1.0.0",
    "@phenomic/preset-react-app": "^1.0.0",
    "eslint": "^4.1.1",
    "react": "^15.0.0",
    "react-dom": "^15.0.0",
    "react-router": "^3.0.0"
  },
  "phenomic": {
    "presets": [
      "@phenomic/preset-react-app"
    ],
    "webpackConfig": "./webpack.config.js"
  },
  "scripts": {
    "start": "phenomic start",
    "build": "phenomic build"
  }
}
```

and the [default webpack.config.js from here](https://github.com/phenomic/phenomic/blob/34055dcec29aae35eb3e624a0c7301a72649d01f/packages/plugin-bundler-webpack/src/webpack.config.js?ts=2)

and when I run `DEBUG=phenomic:plugin:webpack npm start` I get

```
> @ start /Users/ben/Documents/projects/mw_phenomic
> phenomic start

  phenomic:plugin:webpack get middlewares +0ms
  phenomic:plugin:webpack webpack.config.js is failing SyntaxError: Unexpected token import +110ms
  phenomic:plugin:webpack webpack.config.babel.js is failing Error: Cannot find module '/Users/ben/Documents/projects/mw_phenomic/webpack.config.babel.js' +0ms
  phenomic:plugin:webpack default webpack config used +84ms
 ...
```
