### ISSUE TITLE
createContainer() should be compatible with Redux connect()

### ISSUE THREAD

**Issue by yoDon** [phenomic/phenomic#1086]
On Gitter:  "I looked at the code, I think we will have to make a change so our createContainer() can be used with connect()" Maxime Thirouin Jun 11 22:13

**Comment by MoOx** [comment]
Will be closed by 31cd99ef9c98291ff2640009a26dff73aab1ae7a

**Comment by MoOx** [comment]
Should be ok latest alpha!
