### ISSUE TITLE
[plugin-collector-files] Dates are not parsed correctly from collections

### ISSUE THREAD

**Issue by dlindahl** [phenomic/phenomic#1096]
Given the following collection:
```
/
    /posts
        /2017-02-15-my-post.md
```

`plugin-collector-files` parses the date incorrectly as `0201-01-01`.

[On line 112](https://github.com/phenomic/phenomic/blob/374a090438289efb90308ccaaa08916c3312aff8/packages/plugin-collector-files/src/index.js#L112), the date is inferred from the filename. Unfortunately, the `name` value is the full path which includes the `/posts` folder (`"posts/2017-02-15-my-post"`)

`injectDateFromFilename` then tries to use `slice` to extract the date, but it starts at character 0 which includes the `collectionName`. So it thinks the date is `posts/2017` which is not an valid date.

A quick fix could include the following change to line 112 to read:

```js
var filename = pathSegments[pathSegments.length - 1]; // The last substring in the path separated array which represents the base filename
var adjustedJSON = injectDateFromFilename(filename, json);
```

That will provide `injectDateFromFilename` (and thus `formatDate`) with a valid string to work from.

**Comment by MoOx** [comment]
Thanks for reporting the bug. Will handle this!

**Comment by adambet3** [comment]
Vu minh chien
