### ISSUE TITLE
Phenomic doesn't work with Redux

### ISSUE THREAD

**Issue by yoDon** [phenomic/phenomic#1097]
Here is a minimal Redux store example that causes Phenomic's `npm run build` to fail while trying to createRouteFromReactElement().

App.js:
```javascript
import React from 'react';
import { createApp } from '@phenomic/preset-react-app/lib/client';
import { Router, Route, browserHistory } from 'react-router'; // edited per brianjd's comment below
import { Provider } from 'react-redux';  // edited per brianjd's comment below
import { createStore } from 'redux';

const Home = () =>
  <div>
    <p>This is a test of using Redux with Phenomic</p>
  </div>;

function todos(state = [], action) {
  switch (action.type) {
    case 'ADD_TODO':
      return state.concat([action.text])
    default:
      return state
  }
}

export default createApp(() =>
  <Provider store={ createStore(todos) }>
    <Router history={browserHistory}>
      <Route path="/" component={Home} />
    </Router>
  </Provider>
);
```

package.json:
NOTE: Either use alpha.3 as listed below below and hand-patch to apply [the alpha.4 Redux fix](https://github.com/phenomic/phenomic/commit/31cd99ef9c98291ff2640009a26dff73aab1ae7a) or use alpha.4 or master code directly (I believe both approaches result in the same error message).
```javascript
{
  "private": true,
  "devDependencies": {
    "@phenomic/core": "^1.0.0-alpha.3",
    "@phenomic/cli": "^1.0.0-alpha.3",
    "@phenomic/preset-react-app": "^1.0.0-alpha.3",
    "react": "^15.0.0",
    "react-dom": "^15.0.0",
    "react-router": "^3.0.0",
    "react-redux": "^4.0.0",
    "redux": "^3.6.0"
  },
  "phenomic": {
    "presets": [
      "@phenomic/preset-react-app"
    ]
  },
  "scripts": {
    "start": "phenomic start",
    "build": "phenomic build"
  }
}
```

`npm run build` returns:
>TypeError: Cannot read property 'defaultProps' of undefined at createRouteFromReactElement

**Comment by brianjd** [comment]
@yoDon react-router exports a generic provider?

**Comment by yoDon** [comment]
@brianjd I'm not sure if you're asking me about how react-router works or suggesting there is a different syntax that should be tried. I'm happy to try something different, if you have a suggestion (but I'm fairly new to Redux so a detailed suggestion would help)

**Comment by yoDon** [comment]
That example runs fine if you delete the `<Provider store={ createStore(todos) }>` and `</Provider>` lines, btw

**Comment by brianjd** [comment]
@yoDon You are importing `Provider` from `react-router`, rather than `react-redux`.  I was wondering if that's a convenience export they were providing now.

**Comment by thangngoc89** [comment]
Like @brianjd said, `react-router` doesn't have a `Provider` export

**Comment by yoDon** [comment]
@brianjd @thangngoc89 thanks for catching that typo (I've fixed the code above), unfortunately with the correct import phenomic still throws an error:

>plugin-renderer-react\lib\components\Container.js:124: var isLoading = values.some(function (item) {
>TypeError: Cannot read property 'get' of undefined

**Comment by brianjd** [comment]
@yoDon Your store is undefined.  Check the hand patching you did before.

**Comment by yoDon** [comment]
I don't think it's a problem with my store. If I remove the <Provider> everything works fine, and if I include the <Provider> we can see in the code above that the store being passed to the <Provider> is pretty clearly not undefined.

**Comment by MoOx** [comment]
Probably dups of #1086
