### ISSUE TITLE
Allow basic usage of React code inside markdown file

### ISSUE THREAD

**Issue by MoOx** [phenomic/phenomic#1104]
Should be possible with some strong limitations.

Okay @MoOx , thanks!

But what if I want to put a React component in the *middle* of the body somehow, like this:

possible

```markdown
Whatever lorem ipsum

<Expand>
    <Title>See a map of our service territory</Title>
    <Content>
        <img src="./service-map.png" />
    </Content>
</Expand>

Whatever lorem ipsum
```

not possible (as we convert md to json)

```markdown
Whatever lorem ipsum

<Expand>
    { /* js code */ }
</Expand>

Whatever lorem ipsum
```

In short we should accept html like code (the parser can probably help here) that can be mapped to react call.
Should be enough for most generic simple usage (carousel, widgets etc)

For now you can probably yourself use html tags and the `<BodyRender components={{ tag: Component }}` feature.

Thoughts @bloodyowl?

**Comment by MoOx** [comment]
@bherila please not that require() won't be a thing (I adjusted the example)

**Comment by bherila** [comment]
Ok @MoOx thanks, will image URLs be resolved relative to the .md file? Or should I put absolute paths like /public/...

Thank you also for the pointer to the `components` prop, I will try using that!

**Comment by MoOx** [comment]
url are untouched for now, so relative can work, depending on your tree :)
I would go for a absolute one until we work on rewriting path md linked ressources (if it happens)

**Comment by yoDon** [comment]
@medfreeman made a comment on the gitter chat about having done some work in this direction at https://github.com/medfreeman/remark-generic-extensions

His comment https://gitter.im/MoOx/phenomic?at=596cdcdb329651f46e971382 was 

> It supports inline extensions atm, and can be used with remark / phenomic. The example gets you a icon with a tooltip from react-toolbox by writing '!Iconicon-name{parameters}'. Everything is modular

**Comment by revolunet** [comment]
Wondering if we could mix md and react components :)
```
<Expand>
    <Title>See a map of our service territory</Title>
    <Content>
        Some **Markdown**
    </Content>
</Expand>
```

**Comment by bherila** [comment]
Not really, as the content files are parsed by Phenomic and not node/react itself.  For now, this is a blocker for me as well.

**Comment by MoOx** [comment]
Will work on a flexible solution soon.
That will involve a mapping in your JS and will have some limitations but should cover most use cases (since we are using JSON, not JS for content).

**Comment by MoOx** [comment]
FYI since recent releases, we have a map we can pass and all html is accepted so it's already possible. One thing is that all html like names are lowercased during creation of the AST. But you can pass unrecognized xml like tags and use this during rendering. I will close this issue with a example.

**Comment by MoOx** [comment]
Closed by https://github.com/phenomic/phenomic/commit/9631a697f54b682a9bd9fd9eb1120101e9e41279
