### ISSUE TITLE
Cannot we cut the bundle given by phenomic into small chunks?

### ISSUE THREAD

**Issue by PavanGangireddy** [phenomic/phenomic#1108]
phenomic.browser.cebc36f8d53f0fcd5aa7.js is taking so much time initially to load, so i would like to have little help on whether there is any possibility to load a small bundle initially, and then add other after the fold chunks of data?

**Comment by MoOx** [comment]
You can handle this with webpack require.ensure or dynamic import. See https://webpack.js.org/guides/code-splitting/
