### ISSUE TITLE
Static build not working for collections

### ISSUE THREAD

**Issue by daine** [phenomic/phenomic#1114]
After running `npm run build`, if run http-server on the `dist/` folder, the collections doesn't work. I was able to replicate the issue with the phenomic docs code located at: https://github.com/phenomic/phenomic/tree/master/docs

<img width="986" alt="phenomic-news" src="https://user-images.githubusercontent.com/916044/28233244-5a8b5a78-68aa-11e7-983d-ebb7dfd07b26.png">
<img width="368" alt="phenomic-collections-bug" src="https://user-images.githubusercontent.com/916044/28233250-5f9706f2-68aa-11e7-8691-62db900f8a23.png">

**Comment by MoOx** [comment]
I found the issue. It will be fixed in #1111
