### ISSUE TITLE
Support running website from a folder under a root url

### ISSUE THREAD

**Issue by daine** [phenomic/phenomic#1124]
In the previous phenomic version, you can set your homepage & the relative URL of where your phenomic site will reside. In the new alpha, this is not currently possible as it assumes it will reside at the top domain.

This works:
http://mywebsite.com/

This doesn't currently work:
http://someoneelseswebsite.com/mywebsite/

**Comment by PezCoder** [comment]
I would like to work on this. I'm pretty new to this project.
I'm still trying to figure out what functionality phenomic provides, I'll go through the getting-started with react portion once to get a complete idea & will start working on this feature.

As @daine mentioned, in the previous version this functionality was present, I think taking a look at previous commits might help to just include those changes rather than building it again.

**Comment by MoOx** [comment]
v0.x and 1.x are really different so it's not a good idea :)
You should look for hardcoded "/" :D

**Comment by PezCoder** [comment]
@MoOx Sorry, but I'm not clear about the thing that needs to be done here.
From what I understood so far, phenomic cli has two commands `start` & `build`. Build is the one that compiles the application & converts markdown data to create proper html pages that can be served directly from any server with dist as the root.

The folders for this is created based on routes defined for your application i.e if I have a route '/yoda' with some component, phenomic will create a 'yoda' directory inside `dist` with an index.html for that route.

So if an application consuming phenomic needs all of it's routes to be hosted under a URL, Can't they just use the React Router to do just that something along the lines of:
```js
<Routes>
  <Route path="/some/sub/dir">
    <!-- since its relative here, I only have to specify the sub directory once
      which is not really different than a baseUrl option, is it? --> 
   <Route path="foo" />
  </Route>
</Routes>
```
Reference: https://github.com/ReactTraining/react-router/issues/353#issuecomment-58096544

**Comment by MoOx** [comment]
This won't work for the simple reason that phenomic will create additional files with html entries: for js and for json entries (when the client have javascript, only a single html is used per session).

Those files will be created in dist/ so we need to

- replace all "/" by a configurable value
- allow to use a base path for react-router

Here are some places that rely on an hardcoded "/" or that may require an adjustment:

- https://github.com/phenomic/phenomic/blob/69e6f8852e873d995a0c500182be373310befebe/packages/plugin-bundler-webpack/src/webpack.config.js#L17
- https://github.com/phenomic/phenomic/blob/69e6f8852e873d995a0c500182be373310befebe/packages/plugin-renderer-react/src/renderHTML.js#L28
- https://github.com/phenomic/phenomic/blob/69e6f8852e873d995a0c500182be373310befebe/packages/api-client/src/url.js#L6

Maybe there is more.

We should be careful with api (from core) that serve starting /. Files generated during static build should be adjusted. Maybe a simple adjustment during static build can do the trick too (and keep / during dev)

We should be able to "relocate" a site from a path to a root domain without having to change all urls, links and route path. A single config key should do the trick.
