### ISSUE TITLE
[0.21] unicode weirdness

### ISSUE THREAD

**Issue by revolunet** [phenomic/phenomic#1125]
Issue for the record on phenomic@0.21.1

When you have a markdown containing weird unicode chars (ex: pasted from Word), everything looks fine in dev mode but not in production.

Here's the traceback and some info. in my case the ["line separator" invisible unicode character](http://www.fileformat.info/info/unicode/char/2028/index.htm) breaks production.

Will work on a patch right now because this is quite dangerous, so if you have any idea please tell me :)

in the resulting HTML :
<img width="591" alt="capture d'écran 2017-07-24 a 15 48 33" src="https://user-images.githubusercontent.com/124937/28526357-9935193c-7087-11e7-898d-21aa597efc86.png">

traceback :
<img width="1372" alt="capture d'écran 2017-07-24 a 15 41 25" src="https://user-images.githubusercontent.com/124937/28526304-72051c54-7087-11e7-8d2a-85b79505a26a.png">

breakpoint :
<img width="1122" alt="capture d'écran 2017-07-24 a 15 34 23" src="https://user-images.githubusercontent.com/124937/28526306-7414c058-7087-11e7-90b9-137a98ed7a6b.png">

**Comment by revolunet** [comment]
Ok so looks like this is related to node + two json special chars :) https://bugs.chromium.org/p/v8/issues/detail?id=1939

hot patch coming

**Comment by revolunet** [comment]
fun fact : didnt manage to test the code due to these breaking chars in .js files :)
<img width="882" alt="capture d ecran 2017-07-24 a 16 30 06" src="https://user-images.githubusercontent.com/124937/28528259-83371f94-708d-11e7-9068-6ecdf43936d8.png">

Also, looks like i cannot send a pull request to tag 0.21.1 (need a branch).

BTW, heres the fix : https://github.com/phenomic/phenomic/compare/0.21.1...revolunet:unicode-spechars-fix

**Comment by revolunet** [comment]
would be great to merge that fix into a 0.21.2

**Comment by MoOx** [comment]
I just created a branch 0.21.2, feel free to make a PR here.

**Comment by revolunet** [comment]
thanks, done : https://github.com/phenomic/phenomic/pull/1128

**Comment by MoOx** [comment]
Should be fixed by #1128 in 0.21.2
