### ISSUE TITLE
Loading Webpack configuration from ES6+ script fails

### ISSUE THREAD

**Issue by icedream** [phenomic/phenomic#1126]
There is a problem with https://github.com/phenomic/phenomic/blob/c8678c0bf2b24389d2faa8508c4c543b0d99f889/packages/plugin-bundler-webpack/src/index.js#L35-L38 where the plugin expects the exported Webpack configuration to be available directly as the export itself. This works with standard JavaScript where `module.exports` can be used to export the configuration. However if ES6 is used with Babel and the configuration is exported as seen below, the configuration will actually be exported in an object as a field named "default" and the loading of the configuration will fail with this debug error message if Phenomic is run with the environment variable `DEBUG=phenomic:plugin:webpack`:

```
  phenomic:plugin:webpack webpack.config.babel.js is failing TypeError: require(...) is not a function +782ms
```

#### webpack.config.babel.js:
```es6
// This will export the function generating the webpack configuration as "default".
export default (phenomicConfiguration) => {
  let webpackConfiguration = {};
  // ... set configuration values for webpack here ...
  return webpackConfiguration;
};
```

#### .babelrc
```js
{
  "presets": [
    "es2017",
    "es2016",
    "es2015",
  ]
}
```

A workaround would be to just use `module.exports` for exporting instead of `export default`, however this issue wouldn't occur with Webpack itself being used as it reads configurations exported with `export default` just fine.

**Comment by MoOx** [comment]
Next release will handle that.

**Comment by MoOx** [comment]
Should be ok with the new 1.0.0-alpha.5! Please try and tell us if that's better!
