### ISSUE TITLE
Update to React Router 4

### ISSUE THREAD

**Issue by hugmanrique** [phenomic/phenomic#1130]
Hi! It's been half a year since React Training released React Router 4. As the previous version (3) has some bugs and it isn't supported anymore, I think it should be time to update.

[Migration guide](https://github.com/ReactTraining/react-router/blob/master/packages/react-router/docs/guides/migrating.md) from the React Router docs.

I know this is gonna break stuff, but it's a good step in the long run.

**Comment by MoOx** [comment]
Sadly, react-router v4 doesn't play well with static rendering. The simplest reason is that react-router v4 allows nested routes, so it's very difficult for us to predict routes. We have no way to determine all possibles routes. It's basically impossible.
A solution might be to ask users to specify (like next.js export feature) the route to generate statically. But for a static site generator, this sucks. We can all agree with that.
We could also add a restriction: only routes provided at the root of the app could be rendered.
@bloodyowl tried to handle this upgrade, but was stuck at some points.

We are considering to switch to [director](https://github.com/flatiron/director) (or support both, rr 3 & director).

Any comments?

**Comment by hugmanrique** [comment]
Perhaps rendering the routes at the root of the app as default but then requiring an additional file with routes as you suggested might Ok.

The ultimate solution would be to deep inspect all the children of the React Router and get the routes and the associated components.

**Comment by MoOx** [comment]
Problem is: nested routes introduce recursive routes, so infinite possibilities. Not ok for pre-rendering :'(

**Comment by bloodyowl** [comment]
> The ultimate solution would be to deep inspect all the children of the React Router and get the routes and the associated components.

it would imply to render all the app with "empty" store/props and miss routes if they're behind a condition. not ok for us.

**Comment by MoOx** [comment]
Closing in favor of #1136
