### ISSUE TITLE
Phenomic's site server's content is broken

### ISSUE THREAD

**Issue by kbariotis** [phenomic/phenomic#1133]
The content hosted on the server is not correct. After the client side code kicks in the rendering is done correctly.

![screen shot 2017-08-04 at 22 32 55](https://user-images.githubusercontent.com/605742/28984105-0332198a-7965-11e7-8774-b1a6a2fe5d85.png)

Not sure if this is mentioned in another issue.

**Comment by MoOx** [comment]
Thanks. It's only a FOUC related to a bug on the documentation website.
The code in the html you are showing is correct and expected (it's the code in the pseudo editor).
Incoming release (and website update) will handle that.

Thanks for reporting!

**Comment by MoOx** [comment]
FOUC has been fixed. Pretty stupid error from my side fixed in https://github.com/phenomic/phenomic/pull/1134.
For website design errors, tracked in #1045
