### ISSUE TITLE
Switch to a non react-router

### ISSUE THREAD

**Issue by MoOx** [phenomic/phenomic#1136]
Why?

- react-router v4 is not static rendered friendly as explained in #1130 
- relying on react-router v3 (a deprecated version) is not a good idea on the long run
- we need a solution compatible with non react renderers

What we need?

- Routing via params/wildcard
- redirections

We are thinking about https://github.com/flatiron/director.
Thoughts?

**Comment by stefanmaric** [comment]
I'm looking into phenomic as a simpler alternative to Gatsby.

Gatsby uses `react-router@4`, just that their approach seems to be different. They start with pages as entry points and crawl them using [static-site-generator-webpack-plugin](https://github.com/markdalgleish/static-site-generator-webpack-plugin).

Is it possible to use this approach with phenomic?

**Comment by MoOx** [comment]
Gatsby solution is one of the reason why Phenomic has been created. Phenomic allows you to have a full controls on the routes and don't make any assumption.
Also since v1, we are not directly coupled to webpack (that will open up us a lots of door - mostly for speed improvements).

One way to have a simple router is to use a glob and make a query on all pages. Will try to push an examples to offer a dead simple mapping as I am not sure "path" (formerly "collection) for our query API is optional.

@stefanmaric Would you be ok having a router with a single route or does it look like a blocker for you?

**Comment by stefanmaric** [comment]
> Would you be ok having a router with a single route or does it look like a blocker for you?

I haven't actually looked too much into phenomic so I'm not sure what this means in my case.

I would say what I'm looking is something on these lines:

```jsx
const Home = ({ items }) => (
  <ul>
    {items.map(item => (
      <li key={item.id}>
        <Link to={`/items/${item.id}/`}>{item.name}</Link>
      </li>
    ))}
  </ul>
)

const HomeContainer = createContainer(Home, props => ({
  items: query({
    path: 'items'
  })
}))

const ItemDetails = ({ item }) => {
    <div>
      <p>Some content here</p>
      <Route path="/items/:id/overview" component={ItemOverviewContainer} />
      <Route path="/items/:id/reviews" component={ItemReviewsContainer} />
      <Route path="/items/:id/related" component={ItemRelatedContainer} />
    </div>
}

const ItemDetailsContainer = createContainer(ItemDetails, props => ({
  items: query({
    path: 'items',
    id: props.itemId
  })
}))

/*
... pretend the other Item* components are here
*/

const routes = () => (
  <BrowserRouter>
    <Route path="/" component={HomeContainer} />
  </BrowserRouter>
)

export default createApp(routes)
```

**Comment by MoOx** [comment]
Sadly, as explained in https://github.com/phenomic/phenomic/issues/1130, rr4 (mostly because we don't know all possible routes easily - and we can even miss some (eg: infinite nested routes)) is not ok for us. So you will need to have to define all routes in the same place.

**Comment by thangngoc89** [comment]
I was about to suggest director. But I think we can wait a little bit longer. @_chenglou from Reason is working on a new router that type-safe, fast and easy to use.

**Comment by MoOx** [comment]
- does this router will work for js only project?
- last commit being from 2015 does not mean the project is not stable

**Comment by thangngoc89** [comment]
After poking around, Director doesn't seem to be a good fit either. We can actually upgrade to React Router 4 by using react-router-config 

https://reacttraining.com/react-router/web/guides/static-routes

**Comment by MoOx** [comment]
What is the problem with director?
Anyway if phenomic wants to support more than react, the router should be pluggable somehow. Or renderer plugin should assume a router is being used and we should provide an api to "normalize" routing for phenomic so vuejs users can use their own router.
But rr4 + config can be a good idea for react too.

**Comment by thangngoc89** [comment]
Problems with director: 
1. Last commit is from 2015 and it looks like a stale project
2. Doesn't play nice with React Hot Loader (I tried many ways but can't figure out how to do it)

**Comment by MoOx** [comment]
urls-resolver are now part of our plugin APIs. We can now supports as many router as we want via plugins.
