### ISSUE TITLE
PREACT Plugin/preset/example

### ISSUE THREAD

**Issue by MoOx** [phenomic/phenomic#1148]
We can probably reuse a lot of the react plugin (if not everything).

**Comment by marcelorl** [comment]
I'm going to work on this one.

**Comment by MoOx** [comment]
@marcelorl Sure! Do not hesitate to ask!
One thing I would like to do: avoid using preact-compat, but not sure if that's easy if we want to rely on react-router. Feel free to discuss any questions you have here, on our chat!

**Comment by drazik** [comment]
@marcelorl did you start working on it ? If yes, I can help if you want. Otherwise, I can start the work :)

**Comment by drazik** [comment]
I just started to work on this one. Will keep you updated as soon as I have something working. I may have a lot of questions to ask during my work on it.

**Comment by jcayzac** [comment]
> Avoid using preact-compat, but not sure if that's easy if we want to rely on react-router.

react-router works directly with preact, see  https://codepen.io/developit/pen/BWxepY?editors=0010

**Comment by drazik** [comment]
Yes but phenomic uses react-router 3, which is not compatible with preact without preact-compat AFAIK

**Comment by MoOx** [comment]
Not a priority atm. Feel free to discuss below.
