### ISSUE TITLE
Next.js Plugin/preset/example

### ISSUE THREAD

**Issue by MoOx** [phenomic/phenomic#1149]
Can be done since Next.js have a native static export feature.
Should act as a bundler + renderer.

**Comment by omerdn1** [comment]
How can we contribute/see progress on this?

**Comment by MoOx** [comment]
Nothing has been made yet. Want to help?

**Comment by omerdn1** [comment]
@MoOx I would love to, how and with what do you usually start when working on a new platform?

**Comment by MoOx** [comment]
@omerdn1 You can probably check what I said in https://github.com/phenomic/phenomic/issues/1145 and look for CONTRIBUTING.md and get back here if you have any question to be familiar with the codebase

**Comment by ankitsinghaniyaz** [comment]
@MoOx can you please explain what you meant by
> Should act as a bundler + renderer.

**Comment by MoOx** [comment]
Next is currently hiding the usage of webpack. Our react reset use react as a renderer + webpack plugin as a bundler. Next plugin should probably replace this 2 different kind of plugins.

**Comment by MoOx** [comment]
I am reconsidering how Phenomic will be presented to end users, so will have to think about it.
