### ISSUE TITLE
Evaluate the possibility of offering a Graphql interface

### ISSUE THREAD

**Issue by MoOx** [phenomic/phenomic#1151]
Because that can be fun, even if it might produce some overfetching.

We are using leveldb, so we might take a look to https://github.com/levelgraph/levelgraph

**Comment by DominikGuzei** [comment]
To give you some feedback: im testing phenomic atm coming from Gatsby because their GraphQL api is so complicated that i felt like i have to learn a separate data framework which is badly documented - not fun! For the very simple case of showing blog posts you have to write hundred lines of code.

**Comment by MoOx** [comment]
@DominikGuzei that's why we choose this approach. To keep things simple in the first place, that will fit 80% (or more) of the needs.
Welcome then! Be sure to ask questions if you have, via issues, or [our chat](http://gitter.im/MoOx/phenomic)

**Comment by MoOx** [comment]
FYI, this issue has a very low prio :)

**Comment by MoOx** [comment]
#1266 will allow this.
