### ISSUE TITLE
Please add an example with code splitting

### ISSUE THREAD

**Issue by DominikGuzei** [phenomic/phenomic#1152]
Im building a frontend application that will support different UIs for different user roles and each of those sub "apps" might become increasingly complex and i would like to avoid having to load the whole bundle for all users. This will become especially important to keep the landing page snappy while providing a lot of functionality in sub apps!

**Comment by MoOx** [comment]
Good idea. Will do if nobody make this before me :)

**Comment by MoOx** [comment]
Will be part of docs
