### ISSUE TITLE
Support asciidoc

### ISSUE THREAD

**Issue by kepinpin** [phenomic/phenomic#1153]
Please support asciidoc for templating: https://github.com/asciidoctor/asciidoctor.js

**Comment by gandulio** [comment]
I would also love to see this!

**Comment by ezralalonde** [comment]
I had hacked support for asciidoctor for the old Phenomic. It was kind of ugly, but not terribly difficult.

When I move to 1.0 I'll likely do it again. I'm also happy to help out if anybody else is taking this on.

**Comment by ezralalonde** [comment]
This is enough for my needs:

- https://www.npmjs.com/package/phenomic-plugin-transform-asciidoc
- https://github.com/ezralalonde/phenomic-plugin-transform-asciidoc

Let me know if you're having problems or issues with the plugin.

Cheers,

**Comment by MoOx** [comment]
Are you open to get this plugin into our repo? I can add you the write rights for the repo :)

**Comment by ezralalonde** [comment]
I'm 100% open to contributing it to this repo. Thanks!

My task list for the asciidoc plugin to be "official" is roughly:

- [ ] write some tests for the plugin, however basic
- [ ] ensure `plugin-transform-asciidoc` can be used in place of `plugin-transform-markdown` or `plugin-transform-json` without any changes to default/example templates
- [ ] change internal source code style/naming to more closely follow conventions established in other transformers
- [ ] relicence to MIT

I think these are all quite easy. Let me know if there is anything else that comes to mind.

There are some other things that might be nice in the future—having plugins deal with source code in roughly the same manner, autolinking headers in the same way, being able to share CSS—that seem like much more work, and that can be dealt with a little later, if at all. Right now I think these would be a lot of effort for questionable returns. Expecting plugins to coöperate in this way is probably unrealistic (and very painful).

It will be a little while before I have a chance to do this work myself. If anybody else wants to take a try, feel free. I will submit a pull request to this issue when I have something.

Cheers!

PS. I also have very rough "how to write a plugin" notes that I hope to get together at some point, based on my initial experience writing a plugin. 
PPS. Again, it is a credit to everyone who works on Phenomic that I was able to develop this plugin. You are awesome!
