### ISSUE TITLE
Unknown prop `classNames` on <a> tag

### ISSUE THREAD

**Issue by DominikGuzei** [phenomic/phenomic#1154]
When rendering the `first-post.md` from `react-app` example im getting this error:
![screenshot 2017-09-07 um 16 04 38](https://user-images.githubusercontent.com/172414/30168179-e902b10c-93e8-11e7-98e1-3ea820d47354.png)

**Comment by MoOx** [comment]
Fixed in [v1.0.0-alpha.7](https://github.com/phenomic/phenomic/releases/tag/v1.0.0-alpha.7)
