### ISSUE TITLE
SSR warning in development

### ISSUE THREAD

**Issue by DominikGuzei** [phenomic/phenomic#1155]
In the new alpha-6 version im running into this warning:
![screenshot 2017-09-11 um 16 21 35](https://user-images.githubusercontent.com/172414/30279542-ca90a4fe-970d-11e7-90d2-27213fd0794b.png)

**Comment by MoOx** [comment]
It’s because in dev mode I inject a snippet to show if you have an error BEFORE rendering is finished, to avoid you a blank page!
(because blank page are a pain)
(and bad for UX)
Will probably find a trick to avoid the warning. Thanks for reporting!

**Comment by MoOx** [comment]
Fixed in [v1.0.0-alpha.7](https://github.com/phenomic/phenomic/releases/tag/v1.0.0-alpha.7)
