### ISSUE TITLE
Not possible to build while dev environment is running

### ISSUE THREAD

**Issue by ArthurClemens** [phenomic/phenomic#1156]
When building an error is thrown:
```
OpenError: IO error: lock (...) node_modules/.cache/phenomic/db/LOCK: Resource temporarily unavailable
```

This is solved by stopping the dev environment and run build again. But it is confusing.

**Comment by MoOx** [comment]
Will add a proper (and clear) warning or will find a workaround for the db lock.

**Comment by MoOx** [comment]
Explicit error message pushed in [v1.0.0-alpha.7](https://github.com/phenomic/phenomic/releases/tag/v1.0.0-alpha.7)

We might do something better when we will work on database caching.
