### ISSUE TITLE
Showcases on phenomic.io not rendered properly in firefox

### ISSUE THREAD

**Issue by aschrijver** [phenomic/phenomic#1159]
![001_phenomic-feedback_firefox-54-layout-issues](https://user-images.githubusercontent.com/5111931/30468792-7133d880-99ed-11e7-8f7f-355b9c041a1c.png)

Ubuntu 16.04 / Firefox 54.0

The showcases do not display as they should (when compared to chrome) and take _really_ long time to load, when going to next page (or next page not appearing at all)

**Comment by MoOx** [comment]
Thanks for reporting. I am fixing this ATM! :)

**Comment by aschrijver** [comment]
Ah, thx! was already figuring this should be something temporary.. (found also _next_ not working on chrome 60.0.3112.90)

**Comment by aschrijver** [comment]
yeah.. works like a charm again :tada: 

thanx @MoOx !
