### ISSUE TITLE
Warning: Accessing PropTypes via the main React package is deprecated

### ISSUE THREAD

**Issue by DominikGuzei** [phenomic/phenomic#1160]
With the latest alpha versions im always getting this React deprecation warnings:
![screenshot 2017-09-18 um 17 30 47](https://user-images.githubusercontent.com/172414/30550302-5bad3d38-9c97-11e7-8324-fe822a36735c.png)

**Comment by MoOx** [comment]
I saw that. Didn't find yet what package is responsible for this. Will have a look.

**Comment by MoOx** [comment]
This warning seems to be gone with 1 alpha 10 (at least with getting started example). Feel free to reopen if relevant but if you still have it it's probably one of the lib you are using.
