### ISSUE TITLE
Query by param sanity check

### ISSUE THREAD

**Issue by owenhoskins** [phenomic/phenomic#1163]
Hello. Would be nice if someone could sanity check this for me.

Version: 1.0.0-alpha.8.

Querying by "tag" isn't working as I'd expect. I am modeling my structure on phenomic/docs/showcase.

My route definition is like so:

```
  <Route path="/blog" component={ Posts } />
  <Route path="/blog/after/:after" component={ Posts } />
  <Route path="/blog/tag/:tags" component={ PostsByTag } />
  <Route
    path="/blog/tag/:tags/after/:after"
    component={ PostsByTag }
  />
  <Route path="/blog/*" component={ Post } />
```

My Posts containers query:

```
export default createContainer(Posts, props => ({
  posts: query({
    path: "posts",
    limit: 10,
    after: props.params.after
  })
}))

export const PostsByTag = createContainer(Posts, props => ({
  posts: query({
    path: "posts",
    by: "tags",
    value: props.params.tag,
    order: "asc",
    limit: 10,
    after: props.params.after
  })
}))
```

When I build this is what the dist folder looks like: 
![dist-posts](https://user-images.githubusercontent.com/1849997/30643592-e116fe9a-9e0f-11e7-90c6-c64027c51a9b.png)

Compare that to the dist folder of the docs site:
![dist-showcase](https://user-images.githubusercontent.com/1849997/30643596-e45f5e58-9e0f-11e7-9777-921f6a8da0c4.png)

It seems like my `posts/by-tags` folder should contain folders of the tags like `showcase/by-showcaseTags` of the docs site.

My YAML looks like this:

```
---
title: Android Transporter
date: 2012-05-07
tags:
  - Android
---
```

When I navigate to http://localhost:3333/blog/tag/Android the `node.list` object is empty.

If I am missing something I hope the above is revealing. Let me know!

**Comment by MoOx** [comment]
I am seing this

```
path="/blog/tag/:tags/after/:after"
```

```
 value: props.params.tag,
```

params.KEY should match what you used in route, so in your case :tags. Tell me if that fixes your problem :)

**Comment by owenhoskins** [comment]
Problem fixed. Question answered.
