### ISSUE TITLE
Error: none of the files listed in global config root_files are present

### ISSUE THREAD

**Issue by rickyvetter** [phenomic/phenomic#1164]
I run into this interesting error when trying to build out a site that isn't rooted at the same location as version control:

```
root
|- .git
|- website
    |- package.json
```

It's fixed by adding an empty `.watchmanconfig` file as a sibling to your package.json, but it took a while for me to understand the error and find the fix. It would be nice there could be special handling/messaging of this case.

```
events.js:182
      throw er; // Unhandled 'error' event
      ^

Error: resolve_projpath: none of the files listed in global config root_files are present in path `/root/website/content` or any of its parent directories
    at BunserBuf.<anonymous> (/root/website/node_modules/fb-watchman/index.js:95:23)
    at emitOne (events.js:115:13)
    at BunserBuf.emit (events.js:210:7)
    at BunserBuf.process (/root/website/node_modules/bser/index.js:292:10)
    at /root/website/node_modules/bser/index.js:247:12
    at _combinedTickCallback (internal/process/next_tick.js:131:7)
    at process._tickCallback (internal/process/next_tick.js:180:9)
```

**Comment by MoOx** [comment]
That's a weird error and obviously we have to hide this one for something more explicit.
Sadly I am not able to reproduce it.
Our own website is built from a folder (docs) in this repo and I was not able to get this error (and our docs folder has none of the [watchman root_files](https://facebook.github.io/watchman/docs/config.html#root_files) .
Anyway, I tried in another project with the same setup (root with .git + website folder with package.json) and didn't get the error.
Can you share more informations please like node, npm/yarn & watchman version?
Thanks!

**Comment by MoOx** [comment]
Closing due to lack of information.
