### ISSUE TITLE
Missing important line in tutorial for the first post to load

### ISSUE THREAD

**Issue by RVMendoza** [phenomic/phenomic#1176]
CURRENTLY: The tutorial has `BlogPost` component referring to a `Link` component. The tutorial has not instructed to add to the top import to `react-router`, so when the user runs the tutorial exactly as it says, it blows an error and doesn't load the first post as expected.

EXPECTED: The user can follow the tutorial exactly and get the result promised.

TO BE DONE: Add an extra line explaining that they need to update the react-router import to include link

Pull request with changes: https://github.com/phenomic/phenomic/pull/1175

**Comment by MoOx** [comment]
Closed by #1175
