### ISSUE TITLE
How to use conditional component loading for mobile? [ ismobilejs ] 

### ISSUE THREAD

**Issue by xen88** [phenomic/phenomic#1184]
I cannot seem to get **isMobile** to work, I assume because of the _pre-rendering_. I use isMobile to conditionally load different navigation components for web & mobile, which works perfectly in development mode, but once the app is built, the conditional code stops working.

Here is the lib: https://github.com/kaimallea/isMobile
I use isMobile on all my projects and usually works fine in all cases.

**Comment by MoOx** [comment]
This kind of libs need to know where they are running. Sadly pre-rendering make this impossible to use because we are rendering html without knowing where we will run.
You should just decide which kind of html you are going to serve by default (you need to choose depending on your analytics).
That's a limitation of static rendering!

**Comment by xen88** [comment]
Hi @MoOx , I got it working. The solution was to use **state**.

```
{
this.state.ismobile ? <MobileNav /> : <DesktopNav />
}

```
```
componentDidMount() {
   const mobile = typeof isMobile !== "undefined" && isMobile.any;
   this.setState({ ismobile: mobile })
}
```

**Comment by xen88** [comment]
BTW thanks for Phenomic, it's very useful!

**Comment by MoOx** [comment]
componentDidMount is not actually called during react static rendering so that's a solution :)
That said, be careful of the possible "flash of different content" between static (html) and client side hydratation (when react kicks in on the client). That might create an weird feeling for users.

**Comment by xen88** [comment]
The ability to have prerendered seo <head> tags is more important for me. 
I start the component with {opacity: 0} then flip to {opacity: 1} on render to avoid style issues.

Phenomic is so far the only React prerender solution I have found that works properly with SEO, and I have tried React-SSR as well as Prerender.io (both fail with Facebook tags because of the render timing).
