### ISSUE TITLE
Question: Change pagination paths

### ISSUE THREAD

**Issue by DavidWells** [phenomic/phenomic#1188]
Is there a way to change the default pagination paths? 

`http://127.0.0.1:8080/news/after/MjAxNy8wNi9pbnRyb2R1Y2luZy0xLjAuMC1hbHBoYQ==/`

`MjAxNy8wNi9pbnRyb2R1Y2luZy0xLjAuMC1hbHBoYQ==` is hard to look at.

Whats the reason for the random string instead of `http://127.0.0.1:8080/news/after/1/` 2, 3 etc?

**Comment by MoOx** [comment]
Did you completely read our current tutorial? There is an explanation about that https://github.com/phenomic/phenomic/blob/master/packages/preset-react-app/docs/getting-started/5.md

In short: it's not random string at all. It's id in base 64 to allow immutable pagination. A page will NEVER die and will ALWAYS exist and show the exact same content. Like a git commit hash. That's a modern way to make smart and efficient pagination. And for example github is exactly doing that in commit history (eg: https://github.com/phenomic/phenomic/commits/master?after=e3c388e687b9a4d524a8009961df31692f8cfa24+34)

**Comment by MoOx** [comment]
Feel free to continue discussion :)
