### ISSUE TITLE
Queries with no valid parameters send http 200 ok but throw error in console

### ISSUE THREAD

**Issue by MoOx** [phenomic/phenomic#1189]
example 

```js
const PageContainer = createContainer(Page, props => ({
  page: query({}),
}));
```

We should throw from `query()`

**Comment by vikneshwar** [comment]
Hi, I would like to take this up, could you help me get started ? Thanks

**Comment by MoOx** [comment]
@vikneshwar Thanks for offering help!

This file is responsible for handling api response https://github.com/phenomic/phenomic/blob/master/packages/core/src/api/index.js
So you might want to take a look to which route is actually taken and adjust response accordingly :)

**Comment by vikneshwar** [comment]
Hi @MoOx just want to get clarified on few things 

- What do u mean by invalid params ? Any params other that the one configured in that file ? 

- And what response should i send, empty response with status 200 ? 

Thanks

**Comment by MoOx** [comment]
invalid param != no valid params

For you information here are expected params https://github.com/phenomic/phenomic/blob/69e6f8852e873d995a0c500182be373310befebe/flow/interfaces/phenomic.js#L137-L145

You can see here what are the combination possible (as well as in the api file linked previously) https://github.com/phenomic/phenomic/blob/69e6f8852e873d995a0c500182be373310befebe/packages/api-client/src/query.js

The idea is: if in production the file won't exist (because query is likely wrong) we will have a 404 as the json won't have been statically generated. So in dev, we should also get a 404 (with no content as a first step)

**Comment by MoOx** [comment]
#1266 will somehow make this better I guess
