### ISSUE TITLE
Get it working with Typescript?

### ISSUE THREAD

**Issue by mboudreau** [phenomic/phenomic#1203]
I like the idea of the project and would make my life a lot easier, but would really like for this to be using Typescript for my purposes as it makes us more productive and prevents human errors.

Since the webpack build is hidden, it's kind of hard to add typescript as part of the build and I'm not sure where to look as the documentation is lacking.

Any guidance would be appreciated.

**Comment by MoOx** [comment]
There is no hidden webpack build.
The source is actually "just" transpiled with babel and published on npm.

For now our codebase is covered with flow. Here are some types we have defined https://github.com/phenomic/phenomic/blob/master/flow/interfaces/phenomic.js

We should properly only expose somehow the external APIs (some types here may be internals). Then copying this types should not be a big deal I guess.

**Comment by blackwood** [comment]
I'm definitely interested in this too, would be willing to look into making this work.

**Comment by MoOx** [comment]
I guess, when phenomic becomes more used and stable, a binding will shows up.
