### ISSUE TITLE
sub directory

### ISSUE THREAD

**Issue by 0m15** [phenomic/phenomic#1205]
If I create a subdir under `content`, ie. `works`,
I can't get this to work:

`query({ path: 'works' })`

Is it documented anywhere?
I just can't figure out what's the sense of this `path` key in the query.

Thanks.

**Comment by MoOx** [comment]
Hi. Sorry we don't have a proper documentation (yet).
That said, the api-client is really simple https://github.com/phenomic/phenomic/blob/6a593daf159cc325c48d11efa10a9e19267b1bf6/packages/api-client/src/query.js

The query you are passing seems to make sense: you make a query to access content with a path starting with "works".
We are doing the same on our website for the showcase https://github.com/phenomic/phenomic/blob/6a593daf159cc325c48d11efa10a9e19267b1bf6/docs/components/ShowcaseList/index.js#L293

Feel free to share more code or to come on our chat https://gitter.im/phenomic/phenomic

**Comment by MoOx** [comment]
Will be part of docs
