### ISSUE TITLE
Changing the markdown engine?

### ISSUE THREAD

**Issue by HaoZeke** [phenomic/phenomic#1209]
Perhaps I'm missing something but the docs don't mention which engine is used to render the markdown files in phenomic..

I've been looking into phenomic from metalsmith (mainly because my metalsmith configuration takes self-written notes to read now) but I can't switch without pandoc markdown support (my site generates static pdfs of each article)...

Is this a reasonable feature request? Or might I be given some pointers on implementing it myself?

**Comment by MoOx** [comment]
For now it's already possible, but I will clearly say not developer friendly.
We have a plugin that have it's own transformer https://github.com/phenomic/phenomic/blob/master/packages/plugin-transform-markdown/src/transformer.js
We should find a way to provide a custom transformer somehow. 
This transformer use a mix of rehype & remark (via unified) so we can get a AST (react friendly) from the markdown. But I guess it should not be really hard to make this more flexible.

**Comment by HaoZeke** [comment]
So the pandoc AST needs to be transformed to match the mAST which react supports?

**Comment by MoOx** [comment]
Actually we support an AST and HTML too, but HTML is not really great as it rely on dangerousSetInnetHTML - which sucks and is (currently) not supporting internal links (which will trigger normal reload)

**Comment by MoOx** [comment]
Will be part of docs
