### ISSUE TITLE
Error was suppressed when an error happens in webpack.config.js

### ISSUE THREAD

**Issue by thangngoc89** [phenomic/phenomic#1216]
Well, we are using `debug` to show error in that casem but this is super confusing to new people. 

Should change this line https://github.com/phenomic/phenomic/blob/960ff813de0053bc505b702278056ee20f6ec94d/packages/plugin-bundler-webpack/src/index.js#L55  to console.log

**Comment by MoOx** [comment]
After our discussion on gitter, we found that a "module not found" from an import in the config is silenced. We should ensure the error is on the require for webpack file (so may add a fs.stats first) then require it - to avoid this problem.

**Comment by MoOx** [comment]
Closed by 242f6c5eac2a009dc42bcdb73b59feed8e82b64b
