### ISSUE TITLE
Imperative API for navigating

### ISSUE THREAD

**Issue by thangngoc89** [phenomic/phenomic#1218]
`Link` component in plugin renderer-react should provide this out of the box. 

For example:

```js
// Link.js

export const navigateTo = ({pathname, hash, search}) => {
  browserHistory.push({pathname, hash, search})
}
```

**Comment by sergeylukin** [comment]
I was looking for something similar. I have a dashboard page for logged in users, so in my case accessing dashboard route without active session should result in a redirect to home page.
Currently here is what I'm doing:

```js
import { browserHistory } from 'react-router'

...

class Dashboard extends React.Component {
  render() {
    const { user } = this.props
    
    if (!user) {
      browserHistory.push('/')
      return </div>
    }

    return (
      ...app JSX...
    )
  }
}

...
export default connect(
  mapState,
  mapDispatch,
)(Dashboard)
```

...however I'm not happy about it and am looking for a cleaner solution...

@thangngoc89 is this case relevant for your proposal?

**Comment by thangngoc89** [comment]
@sergeylukin yes. This is extractly the usecase I want to support. Just need to baked it into Link component for ease of use

**Comment by sergeylukin** [comment]
@thangngoc89 right, there is some problem with it related to destination route content/url sync on first hit, which is resolved on page refresh (in OS X Chrome at least), however that solution is still not working perfectly fine as it works when a server issues a redirect via HTTP headers, I don't know why. That's the reason I'm still looking for better solution and would love to see this issue brainstormed.

**Comment by thangngoc89** [comment]
@sergeylukin I'll look in to it. I need this feature as well.

**Comment by MoOx** [comment]
React-router is supposed to listen for URL change via history api. So any change via browser API should trigger a router update (in theory at least). Not sure that a navigateTo make sense exported from Link component.

**Comment by thangngoc89** [comment]
I think it too but it doesn’t the case here. I have to use the router props passed down from Route component to do the navigating. And yes it makes sense to me. In Next.js, I can just call the function and make imperative routing everwhere. 

Furthermore, I think that we should use a Router with minimal API surface since we can’t upgrade to RR4 and RR3 doesn’t receive any improvements

**Comment by sergeylukin** [comment]
Just a small note, in order for redirect to work with content loading, reloading the page may be a temporary solution:

```js
export const navigateTo = ({pathname, hash, search}) => {
  browserHistory.push({pathname, hash, search})
  window.location.reload()
}
```

**Comment by MoOx** [comment]
Currently, our only solution rely on RR3 (soon we will provide more). So you should rely on RR `router` context that can handle that via router.push (or for RR4: router.history.push)
Should not be part of our core or a plugin.
