### ISSUE TITLE
Link component: Accept an object as className

### ISSUE THREAD

**Issue by thangngoc89** [phenomic/phenomic#1220]
In redex.github.io app, [bs-css](https://github.com/SentiaAnalytics/bs-css) is used as css-in-js library. But the result is not a string but an object to `toString` method.

React is smart enough to call toString method on the result but `classnames` lib filters it out. 

![image](https://user-images.githubusercontent.com/3049054/34338768-37e8402e-e99e-11e7-836c-9978a6203b5c.png)

**Comment by MoOx** [comment]
Not sure this still make sense. Please reopen if necessary.
