### ISSUE TITLE
Performances improvement

### ISSUE THREAD

**Issue by thangngoc89** [phenomic/phenomic#1224]
This is what's my current build stats looks like on a > 100 pages project.

```
📦 Webpack client build done 49529ms     
📦 Webpack static build done 41573ms
📝 Content processed 46886ms
📃 Pre-rendering finished 2900ms
Done in 144.12s.
```

IMHO this is terrible slow. The content processed part is terribly slow with "pure" js manipulations of in-memory objects.

I raised this issue to investigate about what we can do to optimized the codebase.

**Comment by MoOx** [comment]
May be a problem with your code. I tried with 1000 and 10000 markdown files and didn't see anything too slow. I have a WIP on benchmarks locally, will try to push this soon.

**Comment by thangngoc89** [comment]
I really don’t have anything fancy going on here. See https://github.com/thangngoc89/redex-phenomic

I have tons of json files, convert them 1 to 1 to route.

**Comment by MoOx** [comment]
Don't have time to have a look to this project directly but I will try to push my WIP made with bench as soon as possible.

**Comment by MoOx** [comment]
With my current benchs, I don't see any core "issue" with the build.
Will push a post about some bench soon.
If you find a problem in the core, please reopen.
