### ISSUE TITLE
Implement sort public API 

### ISSUE THREAD

**Issue by thangngoc89** [phenomic/phenomic#1225]
The actual sort function were implemented a while ago here

https://github.com/phenomic/phenomic/blob/33258f441b44302841ebe055319741d3ed985581/packages/core/src/db/index.js#L181

A public API would be needed to be consumed by user

**Comment by MoOx** [comment]
Indeed we need to allow plugin to inject sort function. Probably a map with name => sorting function, and a way to trigger this function via the name in the API?

**Comment by thangngoc89** [comment]
Lol. I have no ideas what're you talking about

**Comment by MoOx** [comment]
The line you mentionned is in db code. The query from the front are converted as url, send to the api server, that access to the db. So if you want anyone to be able to write a sort function, we need a way to ask for the sort via a string only parameter (because: we discuss with url)
