### ISSUE TITLE
while accessing other pages first it is going to homepage

### ISSUE THREAD

**Issue by halloween603** [phenomic/phenomic#1226]
Hii guys,
It is working fine in localhost but in prod if i'm opening any link in new tab first it is showing homepage and then it is redirecting to that link. can anyone help me how to solve this one.
Thankyou

**Comment by MoOx** [comment]
Hi. Can you share some code please? Like routes at least.
Also, can you run the build with `DEBUG=phenomic:core:prerender:resolve npm run build` and share the result?

**Comment by halloween603** [comment]
class PageContainer extends Component {
    componentDidMount() {
        // initializeMautic()
    }
    render() {
        const { props } = this;
        return (
            <PhenomicPageContainer
                {...props}
                layouts={{
                    Page,
                    Homepage,
                    Eureka,
                    Startups,
                    Powerx,
                    Workshops,
                    Mentors,
                    About,
                    Apply,
                    Thankyou,
                    IBGroup,
                    Lead,
                    Programs,
                    PowerToIndia,
                    StartupSchool,
                    HealthHackathon,
                    StartupSchoolUp,
                    StartupKindergarten,
                    IoTWorkshop,
                    Vision,
                    Team
                }}
            />
        );
    }
}

//  <Route path="protected" component={HelloWorld} />
export default (
    <Route component={AppContainer}>
        <Route path="*" component={PageContainer} />
    </Route>
);

**Comment by halloween603** [comment]
export default (
    <Route component={AppContainer}>
        <Route path="*" component={PageContainer} />
    </Route>
);
this is how im specifying our routes

**Comment by MoOx** [comment]
Please surround your code blocks with 
````
```js
js code;
```
````

**Comment by halloween603** [comment]
```js
export default (
    <Route component={AppContainer}>
        <Route path="*" component={PageContainer} />
    </Route>
);
```

**Comment by MoOx** [comment]
Are you using phenomic 0.x?

**Comment by halloween603** [comment]
yeah ^0.20.4

**Comment by MoOx** [comment]
How is your static build file tree?

**Comment by halloween603** [comment]
what does that(static build tree) mean sir,
is it npm run build

**Comment by MoOx** [comment]
The files, on your filesystem. Created by the command.
But issues are for bug and accepted for quick questions. This is not a debug chennal. So please use our chat for this kind of problems http://gitter.im/phenomic/phenomic
