### ISSUE TITLE
[0.x] How to add static files to root

### ISSUE THREAD

**Issue by MrLoh** [phenomic/phenomic#1241]
I am trying to add a `manifest.json` file to my website to add a [native app banner on my website on android chrome browsers](https://developers.google.com/web/fundamentals/app-install-banners/).

I can't figure out, what I have to do to get the `manifest.json` file to be compiled into the build folder. Could anyone help me out.

**Comment by MoOx** [comment]
Did you try to rely on the public folder? Any files in it will end up being at the root. Eg here https://github.com/phenomic/phenomic/tree/master/website/public

**Comment by MrLoh** [comment]
Maybe I'm on too old of a version (`^0.21.1`, I was afraid to update since the structure of everything changed so much) the folder is still called content for me and only the markdown files from it get compiled and moved over and anything in the `assets` sub folder.

**Comment by MoOx** [comment]
Oh I see. Maybe you can use https://github.com/webpack-contrib/copy-webpack-plugin?

**Comment by MrLoh** [comment]
Thanks that sounds like a good solution. 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
