### ISSUE TITLE
API Docs?

### ISSUE THREAD

**Issue by mauricesvay** [phenomic/phenomic#1242]
Is there an API documentation somewhere? I'm looking for all functions, with parameters, etc.
If it doesn't exist, it would great to have one.

**Comment by MoOx** [comment]
To be done :)
I just started working on that!

Meanwhile, you can check this https://github.com/phenomic/phenomic/blob/4cb9661cfa0841ec6ddd0a03839c92fa9990f98e/flow/interfaces/phenomic.js.

(This file will be updated this afternoon with only public types)

Feel free to ask anything you want until something is online!

**Comment by MoOx** [comment]
Docs are a WIP https://phenomic.io/en/packages/core/docs/
