### ISSUE TITLE
Clarify the "Get Starting" tutorial

### ISSUE THREAD

**Issue by bguyl** [phenomic/phenomic#1244]
As I wanted to start quickly, I copy/paste a large part of the code from the tutorial.  
I couldn't make it work and it took me some time to understand why.

On  [page 3](https://github.com/phenomic/phenomic/blob/master/packages/preset-react-app/docs/getting-started/3.md), the blog component is added.  
I didn't pay attention and because there were no `// ...` comment at the end, I assumed the new code had to be add at the bottom.

Thus, because they are function expressions, the order is important and they should be declared before used.

I think the router component should appear in this page to avoid confusion.

**Comment by MoOx** [comment]
Will do. Thanks for the precious feedback. Remember that we have the entire tutorial as example here https://github.com/phenomic/phenomic/tree/master/examples (I will make this more visible in the tutorial so if people have doubts, they can refer to this)
