### ISSUE TITLE
SSR rendering not working for a given react router parameter 

### ISSUE THREAD

**Issue by jcayzac** [phenomic/phenomic#1255]
Using the react app preset, I have this route:
```
<Route path="/p(:id)" component={Page} />
```
Hitting `/p` works fine with the development server, but when I build the static site it generates a page at `dist/p(:id)` instead of `dist/p`, `dist/pfoo`, `dist/pbar`, `dist/pbaz` etc…, so hitting `/p` is a `404`.

**Comment by MoOx** [comment]
The parameter name need to match a given parameter in your data.
We cannot magically resolve all the parameter without a given query.
Can you share some code related (query)?

**Comment by jcayzac** [comment]
Indeed there was no match, my  query was not using the param 👎 
Sorry about that!
