### ISSUE TITLE
No runtime script?

### ISSUE THREAD

**Issue by onionhammer** [phenomic/phenomic#1262]
Is it possible to generate output HTML without the 230kb of JavaScript that phenomic packs in? I'd rather just use phenomic for the layout and build system but make custom vanilla js for my runtime scripting needs

**Comment by MoOx** [comment]
One easy way is just to drop an `Html.js` file and remove the `<Script />`. Eg here https://github.com/phenomic/phenomic/blob/a9a23f66260e55df30de46b75b319e9f4f5b57b7/examples/react-app-blog/Html.js#L28
Js files will be produced but not actually used except for building the html version.
I might add an easy option for that like it was for phenomic 0.x
