### ISSUE TITLE
markdown header causes react error

### ISSUE THREAD

**Issue by onionhammer** [phenomic/phenomic#1263]
This markdown from the phenomic samples appears to cause an error

```md
# This is Markdown
```

Stack trace
```
phenomic.main.js:24095 Warning: Invalid DOM property `class`. Did you mean `className`?
    in span (created by BodyRenderer)
    in a (created by Link)
    in Link (created by BodyRenderer)
    in h1 (created by BodyRenderer)
    in div (created by BodyRenderer)
    in BodyRenderer (at Home.js:71)
```

Looks like it's because the header is automatically creating a 
```
<span class="icon icon-link"></span>
```
and then trying to parse the rendered markdown HTML as react?

**Comment by MoOx** [comment]
Thanks for reporting the error. Are you getting this on the client?
I will try to have a look at it this weekend.
Meanwhile, you can use your own BodyRenderer (by copying this https://github.com/phenomic/phenomic/blob/a9a23f66260e55df30de46b75b319e9f4f5b57b7/packages/plugin-renderer-react/src/components/BodyRenderer.js) and adjusting the behaviour to avoid mapping `class` directly and replace it with `className`.
