### ISSUE TITLE
accessing window.location

### ISSUE THREAD

**Issue by pawel2105** [phenomic/phenomic#1267]
In any of the layouts, when I try to access `window.location` I get a window is undefined error. How can I pass through the react-router location information down to a layout using the `PageContainer` component?

```
const PageContainer = props => (
  <PhenomicPageContainer
    {...props}
    layouts={{
      Page,
      PageError,
      Homepage,
      Post,
      Thought
    }}
  />
);
```

Both the `window` and the `document` object are available when running the app via `npm start` but are not available when running via `phenomic build`.

**Comment by MoOx** [comment]
It's normal. During pre-rendering, it's like server side rendering: the page is not rendered in a browser (for performance reason, amongst others). You need to handle this yourself and test the existence of window/document before using those.
