### ISSUE TITLE
Pages Rendered From Markdown

### ISSUE THREAD

**Issue by oscartbeaumont** [phenomic/phenomic#1268]
How do I create a page that loads its content from a Markdown file? I am building my personal website and I would like to have ```content/index.md``` be the content of my home page while still having the blog content in a subfolder ```content/blog/example-post.md```. I tried
```
const Home = ({ isLoading, page }) => (
  <BodyRenderer>{page.node.body}</BodyRenderer>
);

export default withPhenomicApi(Home, props => ({
  page: query({ path: "content/index.md" })
}));
```
but this does not work. I am using the version ```^1.0.0-alpha.1```.
Thanks

**Comment by MoOx** [comment]
Can you try for the query

‘’’
  path: "content",
  id : "index"
‘’’

.md is not required (removed from the id) and path without id is to get a collection (so partial result).

**Comment by oscartbeaumont** [comment]
So I tried
```
const Home = ({ isLoading, page }) => (
  <BodyRenderer>{page.node.body}</BodyRenderer>
);

export default withPhenomicApi(Home, props => ({
  page: query({ path: "content", id: "index" })
}));
```
and I get an error in the browser console which says ```Uncaught TypeError: Cannot read property 'body' of null```. Using ```JSON.stringify``` I got the content of the ```page``` prop parsed into the ```Home``` component and its output is below. I double checked and the file ```content/index.md``` exists relative to the ```App.js``` in the root of my project.
```{"status":"error","node":null,"error":{"type":"basic","url":"http://localhost:3333/phenomic/content/item/index.json","redirected":false,"status":404,"ok":false,"statusText":"Not Found","headers":{},"body":{},"bodyUsed":false,"error":{}}}```

**Comment by MoOx** [comment]
During loading, node is undefined. So you need to test like in other pages/examples that isLoading is false or that the node is defined.

**Comment by oscartbeaumont** [comment]
So I did that and now in the dev server windows I get the error ```✖ @phenomic: ID 'index' not found in database ('content')``` whenever I load the page in my broswer. The code i'm using is
```
const Home = ({ isLoading, page }) => (
  <div>
    {isLoading && "Loading..."}
    {!isLoading &&
      page.node && (
        <BodyRenderer>{page.node.body}</BodyRenderer>
    )}
  </div>
);

export default withPhenomicApi(Home, props => ({
  page: query({ path: "content", id: "index" })
}));
```

**Comment by MoOx** [comment]
Ha sorry... this id thing is not intuitive... Try “” (empty string).

**Comment by oscartbeaumont** [comment]
Thanks for your help that got it working.
