### ISSUE TITLE
Components with hooks fail phenomic build process

### ISSUE THREAD

**Issue by Jokinen** [phenomic/phenomic#1275]
This can be reproduced in the `react-app-minimal-hello-world` example by upgrading `react` into version `16.8.0` and using hooks:

```jsx
// @flow

import React, { useState } from "react";
import { Router, Route, browserHistory } from "react-router";
import { createApp } from "@phenomic/preset-react-app/lib/client";
// import { createApp, renderApp } from "@phenomic/preset-react-app/lib/client";

const Example = () => {
  const [test, setTest] = useState(false)

  return 'Hello world'
}

export default createApp(() => (
  <Router history={browserHistory}>
    <Route path="/" component={Example} />
  </Router>
));

// uncommment to get hot loading
// if (module.hot) {
//   module.hot.accept(() => renderApp(routes));
// }

```

The error message redirects you here https://reactjs.org/warnings/invalid-hook-call-warning.html

`phenomic start` works fine, so I was caught a bit off guard, but I guess phenomic does a bit of magic when building so it's not completely odd. Any idea on when hooks become usable?

Using latest version from `next`.

**Comment by MoOx** [comment]
Thanks for reporting.
This was due to SSR that were using 2 versions of the same react (one compiled in webpack bundle, one not...). I fixed it by adding react & react-dom as external deps for static rendering.

So Hooks should work with latest beta (10). Enjoy!

**Comment by Jokinen** [comment]
Thanks for the explanation and quick fix!
