### ISSUE TITLE
Add Search capabilities

### ISSUE THREAD

**Issue by MoOx** [phenomic/phenomic#142]
Should be very easy since we have collections to search in all meta (title, tags etc) - but not in body of the posts.
Maybe agolia can help for the body (ref https://github.com/putaindecode/putaindecode.io/issues/535)

**Comment by thangngoc89** [comment]
This is interesting. We can make a different md-collection-loader for generating data and feed it with algolia

**Comment by MoOx** [comment]
Yeah an option like for rss feed.

**Comment by thangngoc89** [comment]
How about a different loader or maybe a new package (like a plugin) ?

**Comment by thangngoc89** [comment]
I think this should not be in the core. This belongs to a plugin. Already done this. See https://github.com/thangngoc89/blog/blob/aa40e1b710c06112006ac175972338467adb56b3/web_modules/utils/statinamic-agolia-plugin.js

Generate feed should be done this way too. No need for debounce trick (faster markdown build)

**Comment by thangngoc89** [comment]
We can borrow idea from https://blog.algolia.com/instant-search-blog-documentation-jekyll-plugin/

**Comment by MoOx** [comment]
Also interesting http://lunrjs.com/

**Comment by thangngoc89** [comment]
This is what it takes to add agolia to a Statinamic site

https://github.com/thangngoc89/dnh-blog/commit/21b07d842a3fd40a5ee362483ba1906cfcd09b55

Demo: http://blog.daynhauhoc.com/

**Comment by MoOx** [comment]
ETA?

**Comment by thangngoc89** [comment]
Lunr.js or algolia ?  Or a simple component that search collection ?

**Comment by MoOx** [comment]
We might offer the choice during setup and/or have the simplest solution (without third-party) and offer a doc to add another solution.

**Comment by thangngoc89** [comment]
I'm on it. 

# TODO:

- [ ] Build index
- [ ] Reduce api requests to Algolia on each build by hashing the page content and only send changed page.

# Resources: 

- https://blog.algolia.com/instant-search-blog-documentation-jekyll-plugin/
- https://blog.algolia.com/how-to-build-a-helpful-search-for-technical-documentation-the-laravel-example/

# Example record 

```
{
    "h1": "Validation", 
    "h2": "Working With Error Messages", 
    "h3": "Custom Error Messages", 
    "link": "validation#custom-error-messages", 
    "content": "If needed, you may use custom error messages for validation instead of the defaults. There are several ways to specify custom messages. First, you may pass the custom messages as the third argument to the `Validator::make` method:", 
    "importance": 6, 
    "_tags": [
        "5.1"
    ], 
    "objectID": "5.1-validation#custom-error-messages-380c9827712413dbe75b5db515cd3e59"
}
```

**Comment by thangngoc89** [comment]
Algoliasearch jekyll added a `lazy_update` feature the reduce the api calls to Algolia https://github.com/algolia/algoliasearch-jekyll/commit/16e7b74b9e6a560af45afbf85ad31a8733fd66dc

**Comment by MoOx** [comment]
This might also be interesting to check out http://fusejs.io/

**Comment by bloodyowl** [comment]
Considering doing a plugin for this

**Comment by MoOx** [comment]
Will revisit this idea later.
