### ISSUE TITLE
Static comment system

### ISSUE THREAD

**Issue by MoOx** [phenomic/phenomic#312]
This, in JS, and with easy doc/setup http://ummels.github.io/jekyll-aws-comments/setup/

**Comment by thangngoc89** [comment]
The project is good. But it's jekyll specific. I would love to have something more generic.

And the docs is talking about jQuery :-1: :-1: :-1:

**Comment by MoOx** [comment]
The thing to keep is the concept, not the code.

**Comment by thangngoc89** [comment]
Oh. I thought you're gonna use the code. Maybe this deserve its own repo.

**Comment by MoOx** [comment]
Definitely.

**Comment by MoOx** [comment]
https://github.com/jimpick/lambda-comments

https://jimpick.com/2016/05/05/introducing-lambda-comments/

**Comment by MoOx** [comment]
Also interesting

https://github.com/mpalmer/jekyll-static-comments
https://github.com/pathawks/jekyll-disqus-comments

**Comment by MoOx** [comment]
https://github.com/eduardoboucas/staticman seems to be the solution. Super easy to implement. We need to try this and document it!

**Comment by MoOx** [comment]
Will be part of docs
