### ISSUE TITLE
Consider google analytics autotrack

### ISSUE THREAD

**Issue by MoOx** [phenomic/phenomic#384]
Even simpler to integrate that the current tracking method of the docs

https://github.com/googleanalytics/autotrack

Maybe to close #428 :)

**Comment by MoOx** [comment]
https://gist.github.com/liesislukas/da29cc8e0e7f44d43251e77f1d0415e8

**Comment by MoOx** [comment]
@liesislukas I don't understand why in your gist you are manually calling pageview on route change. Isn't autotrack supposed to handle this?

**Comment by MoOx** [comment]
Tell me what you think about this https://github.com/MoOx/react-toulouse/commit/c42045d1001ab813c5d7eae5ab2f4f8c08c0025e

I think it's the easier solution to integrate in phenomic.

**Comment by xuopled** [comment]
so is it documentation ready ?

**Comment by MoOx** [comment]
Not yet.

**Comment by MoOx** [comment]
Will be part of docs later
