### ISSUE TITLE
FAQ: I open index.html after build and the page has no styling

### ISSUE THREAD

**Issue by thangngoc89** [phenomic/phenomic#452]
Use a webserver to serve it.

Like [http-server](https://npm.im/http-server) or you can tell Phenomic to run a server for build result with this command: 

```
$ npm run build -- --server
```

**Comment by bloodyowl** [comment]
Going to be fixed with #925

**Comment by MoOx** [comment]
You sure about that? You plan to use relative urls? We already got plenty of problem with relatives urls, not sure it's a good idea.

**Comment by bloodyowl** [comment]
it's basically just a command that runs a `express().use(express.static("./dist")).listen(port)`

**Comment by MoOx** [comment]
Will be part of docs
