### ISSUE TITLE
Add redirection via react-router

### ISSUE THREAD

**Issue by thangngoc89** [phenomic/phenomic#628]
This line https://github.com/MoOx/phenomic/blob/2b44e19bfa095d2a4bb512c122dbb24380a83ef1/src/static/to-html/url-as-html.js#L71

Instead of throwing an error, generate a page with meta tag for redirection. 

For wildcard support, should give a look at Github 404.html file. 

TODO:
- [ ] Single page
- [ ] Wildcard support

**Comment by MoOx** [comment]
See https://github.com/reactjs/react-router/blob/master/docs/API.md#redirect

**Comment by DavidWells** [comment]
This is interesting: https://github.com/auth0/blog/blob/c0bd3926d108ca80b302354aa868c83f9a50a65b/_plugins/alias_generator.rb#L80

Handling redirects via meta refresh.

So basically if a post has `alias` in the frontmatter the build process creates that HTML with redirect. https://github.com/auth0/blog/blob/c0bd3926d108ca80b302354aa868c83f9a50a65b/_plugins/alias_generator.rb#L81-L90

```
new-post-slug-blah.md
alias: /2015/10/07/refresh-tokens-what-are-they-and-when-to-use-them/ 
```

if someone hits: `/2015/10/07/refresh-tokens-what-are-they-and-when-to-use-them/ ` they hit the html with meta refresh that takes them to the new 'correct' URL `/new-post-slug-blah`

**Comment by thangngoc89** [comment]
@DavidWells I planned this as well. I have a wip branch here https://github.com/MoOx/phenomic/tree/feat/redirection but I don't have time to continue the work (yet). Will look into it later

**Comment by MoOx** [comment]
The alias thing is a good idea.

**Comment by MoOx** [comment]
Closing in favor of #1136
