### ISSUE TITLE
Docs: How can I disable phenomic-HeadingAnchorbeing added in the .md loader?

### ISSUE THREAD

**Issue by MoOx** [phenomic/phenomic#666]
Response by pieces here https://gitter.im/MoOx/phenomic?at=57bd7659187885ef4f72db84
Need to be added into faq

**Comment by thangngoc89** [comment]
How about the default markdown preset allow user to alter the remark plugins stack without rewrite a new preset?

**Comment by MoOx** [comment]
I was thinking about that too :D

**Comment by thangngoc89** [comment]
This question was ask twice today on gitter.

**Comment by MoOx** [comment]
Not here by default since 1 alpha 10
