### ISSUE TITLE
Add a way to consume Wordpress API

### ISSUE THREAD

**Issue by MoOx** [phenomic/phenomic#719]
I need this.
The real idea is open Phenomic to consume anything. Ref #713 that will involve changes in how we collect data.

**Comment by thangngoc89** [comment]
AKAIK, webpack can consume files only. So even if we have a nice API, that API has to write some files down. That's what I'm doing with http://cpp.daynhauhoc.com

**Comment by bloodyowl** [comment]
not an issue IMO. if the user write a file containing all its data requirements, we just need to accept a `() => Object | Promise<Object>`, this way the user can use webpack `require.context` or `fetch`. although we have to note that in any case we lose hot reloading on file contents with this.

**Comment by MoOx** [comment]
Not a real issue indeed, might end up as a page in the doc :)

**Comment by DavidWells** [comment]
Love it! @MoOx looking forward to seeing how it's done.

This could be a big step toward allowing folks to port out of Wordpress into a modern and secure stack =)

It would also open the door for some other API usecases like grabbing content from https://www.contentful.com/ 's API.

**Comment by muhajirframe** [comment]
Any update on this ? Can we use contentful right now?

**Comment by MoOx** [comment]
Nothing has been made. I would recommend for now to make a simple script to get contenful content and transform it as markdown files.

**Comment by MoOx** [comment]
Coming in next release of v1
