### ISSUE TITLE
Docs: How to add navigation breadcrumbs

### ISSUE THREAD

**Issue by DavidWells** [phenomic/phenomic#722]
I figured out a way to add breadcrumb nav to our new site:

![image](https://cloud.githubusercontent.com/assets/532272/18228655/7db578c0-720c-11e6-8be7-5d47962ebc7a.png)

It's tough with all routes going through `*` routing but I managed to get it working with a build script + a component

I'm wondering if this might be a good additional to phenomic core?

**Comment by thangngoc89** [comment]
This is absolutely a good additional to phenomic core. Does the breadcrumb reflect the route? 

I think you can do this easier by reading the window.collection

**Comment by DavidWells** [comment]
Yeah it might be easier with window.collection but only if we normalize the window.collection data

We need to be able to lookup pages by a key  (maybe URL slug as key?) instead of filtering the array each time.

**Comment by MoOx** [comment]
Curious to see the code you used for the Breadcrumb. This might ends up as a component we can sheep if that make sense :)

**Comment by DavidWells** [comment]
This is the breadcrumb component: https://github.com/serverless/site/blob/master/src/components/Breadcrumbs/Breadcrumbs.js

and here is how it's being used: https://github.com/serverless/site/blob/master/src/layouts/Doc/index.js#L146

Right now it assumes that all URLs in the path exist. Do everything in our site have an index.md in it.

But it could be wired up to cross reference the collection to check if URL exists first and if the URL does map to a .md file it will add the `<Link>` component. (otherwise it would display the name but not link it)

I am generating a normalized view of the directory structure for faster URL lookups https://github.com/serverless/site/blob/master/src/layouts/Doc/generated-menu.js . This code is generated by this https://github.com/serverless/site/blob/master/scripts/docs/doc-menu-generate.js (excuse the dirty code =P )

It would be nice to simply use the `collection` but I don't want to loop over an array to check each object for the matching URL. A normalized view of the collection gives that constant lookup time. 

Perhaps it would make sense to refactor collection to an object with `url` as the key?

**Comment by MoOx** [comment]
User land problem
