### ISSUE TITLE
Generate routes for data coming in from outside phenomic

### ISSUE THREAD

**Issue by ben-eb** [phenomic/phenomic#732]
Currently, pages such as http://cssnano.co/optimisations/discardDuplicates will respond with a 404 error code on initial load, then the routing will kick in and display the page. This is because the data for this page comes from outside phenomic:

https://github.com/ben-eb/cssnano/blob/2ad9e47263efc6581dec1cd45ad1b2e20b9d49ab/docs/web_modules/app/metadata.js#L27

The page is then routed here:

https://github.com/ben-eb/cssnano/blob/2ad9e47263efc6581dec1cd45ad1b2e20b9d49ab/docs/web_modules/app/routes.js#L32-L35

And the page itself:

https://github.com/ben-eb/cssnano/blob/2ad9e47263efc6581dec1cd45ad1b2e20b9d49ab/docs/web_modules/layouts/Optimisations/show.js#L18

Ideally, we should be able to tell phenomic that this is a real page somehow, so that a 404 isn't thrown.

**Comment by MoOx** [comment]
I will implement a workaround so you can have this before we handle the big change related to #713 :)

**Comment by bloodyowl** [comment]
Going to be fixed with #925

**Comment by MoOx** [comment]
Coming in next release of v1
