### ISSUE TITLE
Use babili instead of UglifyJS

### ISSUE THREAD

**Issue by thangngoc89** [phenomic/phenomic#733]
https://github.com/babel/babili

I have no idea how UglifyJS or babili works under the hood, so I'm posting this to get responses from everyone. Shall we do it now? Or wait until it's more mature.

**Comment by kevin940726** [comment]
I believed that we kind of need to support older browser, as babili actually only minify es6 code without transpiling to es5.

**Comment by MoOx** [comment]
transpilation to es5 is also handled by babel, so not sure this is an issue.

**Comment by bloodyowl** [comment]
Going to be fixed with #925 (moving to user-land)

**Comment by marcelorl** [comment]
@MoOx how about https://github.com/babel/babel-preset-env
??

**Comment by thangngoc89** [comment]
@marcelorl preser env is unrelated to this thread

**Comment by MoOx** [comment]
@marcelorl we are already using this thing, and indeed, nothing to do with compression.

**Comment by MoOx** [comment]
Closing as I won't to rely on something without having to think about it.
