### ISSUE TITLE
React-router v4

### ISSUE THREAD

**Issue by MoOx** [phenomic/phenomic#742]
Well, `<Route>`s are gone... We will have work to thing about that. Maybe things will become even better, not sure yet...

https://react-router.now.sh/basic

**Comment by DavidWells** [comment]
Interesting. Looks like `<Route>` is now `<Match pattern="/about" component={About} />`

**Comment by DavidWells** [comment]
https://www.youtube.com/watch?v=Vur2dAFZ4GE (new router stuff discussed after first 20min)

Looks super cool

**Comment by thangngoc89** [comment]
Super cool!

**Comment by MoOx** [comment]
We will need some requirements to be able to resolve all possible routes for generating the html files. Not what is the best approach here.

**Comment by bloodyowl** [comment]
nope for now (not statically analysable)

**Comment by MoOx** [comment]
Depending on the future of react-router v3, I guess we might have to use another solution.

**Comment by MoOx** [comment]
Final API is not very similar for v4.
Eg: https://gist.github.com/mjackson/33f51e9d6b9ea18b467c613fbbcf50e1

We could require some restrictions about the place people define their routes.

**Comment by bloodyowl** [comment]
I'd advice not to rush into it. We can wait until we release 1.0, and add support for this later. RR4 doesn't really improve anything for phenomic

**Comment by MoOx** [comment]
Yeah sure, I was more pasting this gist to show the minimal required diff :)

**Comment by bloodyowl** [comment]
Yeah for users, in our hands it means much more work 😅

**Comment by MoOx** [comment]
Closing in favor of https://github.com/phenomic/phenomic/issues/1136
