### ISSUE TITLE
Idea: Enhanced <Link> component

### ISSUE THREAD

**Issue by DavidWells** [phenomic/phenomic#816]
I came up with an idea that could potentially remove the need for a `window.collection` object all together.

**Here it goes:**

Instead of having the entire collection on the page, you could have every link add html attributes to the given link on the page. 

If a link doesn't exist on the page, we don't really need access to it in the `window.collection` object because the visitor can only click on links that are shown/rendered on the page they are currently on.

An enhanced Link component:

``` js
<Link to='my-url/here'>Go</Link>
```

Renders to:

```
<a data-page-title='Blah' data-page-data='pagexyz.8b00e61b1e4b8317fd835cde330c124e.json'>Go</a>
```

Then on hover/click the `json` is fetched just like it is now and then the route is rendered.

This setup would mean that all links would just render the minimal amount of data required to link to pages.

So if you have a page that links out to 7 other pages on your site, you would have 7 `<a>` tags rendered with the `data-attributes` needed to fetch the `json` for those 7 routes.

**Potential Drawbacks**

Some people might want access to the entire collection, but perhaps this should be explicit in the page component they are rendering. (or lazy loaded into the dom for everyone)

**Comment by MoOx** [comment]
Just one question: if we remove collection, you do you handle pages listing?
Not sure it's that easy to remove the collection. Somehow it must be used for listing.

I am more thinking about removing the current Link component we have, to make things simpler. I guess we can handle the real problem (smaller build) with other solutions.

**Comment by DavidWells** [comment]
I think the collection API should still exist and be used for listing pages/pagination but might not be required for every page.

pseudo code:
```
import collectionAPI from 'phenomic'

render() {
 const posts = collectionAPI(stuff) // injects the collection into window/built html
  return (
    <div>{loop of posts}</div>
  )
}
```

For smaller sites this doesn't matter. 

For large sites (300+ pages) the large collection starts becoming a performance issue with large 1mb+ html file being downloaded. 

Just trying to think ahead for site growth =)

**Comment by MoOx** [comment]
The thing is: currently __url in collection are used to validate url before requesting the data. So not sure how to handle this. Sounds pretty hard to only includes chunk urls for Link currently rendered: this will assume we know every possible state of your website and if you play with componentWillMount or stuff like that, we are in the shit.

I will for now allow an option to use a js instead of inlining the collection in every files

**Comment by DavidWells** [comment]
Yeah it is limiting on super super dynamic sites.

Hmmm. Back to drawing board. 

I know there is something we can do to start mitigating data size somewhere. =)

A couple potential options:

### 1. smaller `window.collection` object sizes, only link to `.json` reference.

Change 
```js
{
    "layout": "Doc",
    "comments": true,
    "title": "API Gateway Event configuration",
    "menuText": "API Gateway Event config",
    "gitLink": "/docs/02-providers/aws/events/01-apigateway.md",
    "description": "API Gateway Simple http setup This setup specifies that the index function should be run when someone accesses the API gateway at…",
    "__filename": "framework/docs/providers/aws/events/apigateway.md",
    "__url": "/framework/docs/providers/aws/events/apigateway/",
    "__resourceUrl": "/framework/docs/providers/aws/events/apigateway/index.html",
    "__dataUrl": "/framework/docs/providers/aws/events/apigateway/index.html.4ad1407177a073d3c89a28fb94341011.json"
}
```

to: 

```
{
     "__url": "/framework/docs/providers/aws/events/apigateway/",
    "__dataUrl": "4ad1407177a073d3c89a28fb94341011.json"
}
```

This would mean markdown filenames will need to be the route. But perhaps that limitation is ok?

### 2. Flatten the paths to `.json` data files. 

Change `{"__dataUrl":"/framework/docs/providers/aws/events/apigateway/index.html.4ad1407177a073d3c89a28fb94341011.json"}` 

to `{"__dataUrl":"4ad1407177a073d3c89a28fb94341011.json"}` and have all .json files live in a `/data` folder and are put there on `phenomic build`

### 3. Pagination + lazy load `window.collection` after lets say 1000 items

If  `<script src='path/to/collection.json'>`  gets above a certain size, lets say 1MB, we split it into seperate files and load the individual files via a `manifest` file. 

The manifest would act as a reference point to where each `collection.json` data file lives

example manifest file:
```
{
 ["path/to/collection.json", "path/to/collection2.json]
}
// maybe even break up by post type? 
```

**Comment by khrome83** [comment]
@DavidWells I think you could still keep the route attribute in the data next. I think this is very much needed. Why do you think we are limited to just the `*.md` file names?

**Comment by bloodyowl** [comment]
Going to be fixed with #925 (moving to user-land)

**Comment by MoOx** [comment]
Are you sure removing Link is a good idea? How can we handle active state without it? Cause the "/" being "/index.html" is not solved automatically (that's why we have a Link currently.

**Comment by bloodyowl** [comment]
active state is resolvable because it's defined statically, within the router now

**Comment by MoOx** [comment]
Problem is / & /index.html will point to the same content but currently react-router consider it's 2 different urls. That's why there is something specific in phenomic for now.

**Comment by MoOx** [comment]
Will be considered in a future release of v1
