### ISSUE TITLE
Default markdown engine: some html does not work in markdown files

### ISSUE THREAD

**Issue by MoOx** [phenomic/phenomic#817]
Does not work

```
<iframe src="//slides.com/maxdow/toulousejs13/embed" width="576" height="420" scrolling="no" frameborder="0" webkitallowfullscreen mozallowfullscreen allowfullscreen></iframe>
```

(displayed as raw code, wrapped by a `p`)

Works

```
<iframe src="//slides.com/maxdow/toulousejs13/embed" width="576" height="420" scrolling="no" frameborder="0" webkitallowfullscreen="true" mozallowfullscreen="true" allowfullscreen="true">
</iframe>

// or

<iframe src="//slides.com/maxdow/toulousejs13/embed" width="576" height="420" scrolling="no" frameborder="0">
</iframe>
```

It seems current parser does not like attributes without value

(scroll right to see the diff)

**Comment by bherila** [comment]
FYI: Appears that `<button>` suffers from the same problem.

**Comment by daine** [comment]
Most of the html tags I've tried so far doesn't work either.

`<div>` `<p>`  `<span>` - Doesn't show up
`<a>` - Shows up, but only as a paragraph (`<p>`), so no links.

**Comment by MoOx** [comment]
Which version of phenomic?

**Comment by daine** [comment]
I'm using version 1.0.0-alpha.4

**Comment by MoOx** [comment]
I guess are both using 1 alpha :)

**Comment by MoOx** [comment]
On it.

**Comment by MoOx** [comment]
Closed by https://github.com/phenomic/phenomic/commit/1bd1d2f6f15a12082d07061bdc25d46aaae1b86f
