### ISSUE TITLE
Feature request: Access to dev (possibly prod) html template

### ISSUE THREAD

**Issue by DavidWells** [phenomic/phenomic#826]
After some tinkering around on our site. I realized that including the Auth0 lock library adds `702kb` to our bundle output. yikes!

I decided to use their cdn instead to leverage caching on this larger package.

The production build works great when I use  `webpack.DefinePlugin` to reference the global window object included from the script: `https://cdn.auth0.com/js/lock/10.4/lock.min.js`

``` js
new webpack.DefinePlugin({
  Auth0Lock: 'Auth0Lock',
  'window.Auth0Lock': 'Auth0Lock'
}),
```

However in dev, the `<Helmet>` component inside phenomic.js doesn't load before my redux store (where the auth initiates) so the cdn version of the script isn't injected into the page yet and I get reference errors.

I can hack around this if I keep the local package in my project and keep referencing it like so:

``` js
if (process.env.NODE_ENV === 'development' && isClient) {
  var Auth0Lock = require('auth0-lock').default
}
```

But this is less than ideal and keeps this large ass package in my local dev build (aka slow city)

I would really like access to the HTML to include the cdn script tag before the phenomic bundle bootstraps.

I thought of 2 ways to do this:
1. get access to https://github.com/MoOx/phenomic/blob/17fcdf68b10a6af70ed552e4b452b792806b638e/src/builder/server.js#L138 . I'm not exactly sure how, perhaps a scripts field in the phenomic in package.json

``` json
  "phenomic": {
    "CNAME": true,
    "cache": true,
    "offline": false,
    "headerScripts": { "https://cdn.auth0.com/js/lock/10.4/lock.min.js" }
  },
```

Or maybe giving the user the ability to specify custom index.html. This would be [read here](https://github.com/MoOx/phenomic/blob/17fcdf68b10a6af70ed552e4b452b792806b638e/src/builder/server.js#L138) and inject the needed `window.collection` and `<div id="phenomic">` if they are missing

``` json
  "phenomic": {
    "CNAME": true,
    "cache": true,
    "offline": false,
    "indexTemplate": "./path/to/my/custom/index.html"
  },
```
1. Or leverage webpack and use https://www.npmjs.com/package/add-asset-html-webpack-plugin to inject my custom scripts however, I tested this and it doesn't work not sure exactly why. I believe this is due to it relying on `html-webpack-plugin` https://github.com/SimenB/add-asset-html-webpack-plugin/blob/master/src/index.js#L11

Happy to help implement / brainstorm on this as well.

**Comment by DavidWells** [comment]
`<Helmet>` works for production but won't work in this case in dev b/c redux runs before any components mount

**Comment by DavidWells** [comment]
OR perhaps we could have custom phenomic Plugins for these 'hooks' like:

```
new PhenomicAddScript({
      src: 'https://cdn.auth0.com/js/lock/10.4/xxx.min.js',
      async: true,
}),
```

**Comment by MoOx** [comment]
I guess the best idea is to implement a simple solution that allow everyone to add anything in head and or body.
What do you think about adding support for files from config?

```js
{
  "phenomic": {
    "html-template-addons": {
      "head-start": "path/to/partial/file.html",
      "head-end": "path/to/partial/file.html",
      "body-start": "path/to/partial/file.html",
      "body-end": "path/to/partial/file.html",
    }
  }
}
```

Like you mentionned we could support and html files, but since phenomic have to inject some stuff, maybe just supporting "hooks" is simpler to avoid issues.
Thoughts?

**Comment by DavidWells** [comment]
Yeah this would work!

You should be able to define these in the `package.json` or in the `phenomic` config in webpack. The webpack way will let people use different templates depending on 'prod' or 'dev'

**Comment by DavidWells** [comment]
Is this the production HTML https://github.com/MoOx/phenomic/blob/master/src/static/to-html/Html.js#L12-L34?

And this is the dev only HTML https://github.com/MoOx/phenomic/blob/master/src/builder/server.js#L141-L173?

I can take a stab at implementing this as well.

**Comment by MoOx** [comment]
Yeah that's it! Thanks @DavidWells.

**Comment by DavidWells** [comment]
Does the production version need to be rendered via JSX?

**Comment by MoOx** [comment]
I think it's not a requirement but I found this to be more flexible.
I was thinking to reuse the same Html component to render dev server in the future.

If you try to change this you will have to be careful here https://github.com/MoOx/phenomic/blob/9cd247dbba1b5ba9bf6bbb5869c034e723c90087/src/static/to-html/url-as-html.js#L141-L154

**Comment by DavidWells** [comment]
I will probably keep it jsx then.

The question is, how should I get access the `phenomic` config block and pass it through https://github.com/MoOx/phenomic/blob/9cd247dbba1b5ba9bf6bbb5869c034e723c90087/src/static/to-html/url-as-html.js#L147-L151 ?

It looks like `offlineConfig` is getting passed in from somewhere up the chain

**Comment by MoOx** [comment]
Take a look here https://github.com/MoOx/phenomic/blob/9cd247dbba1b5ba9bf6bbb5869c034e723c90087/src/static/to-html/index.js#L59

**Comment by DavidWells** [comment]
This flow shit is hard to read... =P

I'll pick this up tomorrow. Thanks for pointing me in the right direction

**Comment by MoOx** [comment]
Yeah I know, it's hard for me as well. Some part probably need a lot of refactoring :D

**Comment by MoOx** [comment]
I am not a fan at all of adding this option, but just in case I added an undocumented door:

Since https://github.com/MoOx/phenomic/commit/2b184482777193c348ec741e8d731b33887c2764 you can inject your own Html component (based on this one https://github.com/MoOx/phenomic/blob/2b184482777193c348ec741e8d731b33887c2764/src/components/Html/index.js)

**Comment by DavidWells** [comment]
Oh nice. 

What does the config look like?

I had to disabled sentry error tracking from our main bundle b/c it needs to load outside bundle.js before everything bootstraps.

**Comment by MoOx** [comment]
Since 1.0.0-alpha.{something around 8} you have an Html component that's used in dev and prod.
