### ISSUE TITLE
Transform front-matter markdown metatada into html

### ISSUE THREAD

**Issue by xuopled** [phenomic/phenomic#884]
When I put some markdown into metadata, I want get html strings.

```markdown
---
myfield: |-
    **Title**
    content
myarray:
- title: Title
  description:  |-
      **Title**
      content
---
lorem
```

Like the `phenomic/lib/loader-plugin-markdown-transform-body-property-to-html` plugin, we should write a `loader-plugin-markdown-transform-metadata-property-to-html` plugin

**Comment by thangngoc89** [comment]
This should not be default, just write a plugin so that user can add it easily.

**Comment by MoOx** [comment]
I want to make this the default behavior. Lot's of people expect this according to feedback on our chat.
But we will have to be careful for things like "title" that must be able to be used in `<title>`.

**Comment by thangngoc89** [comment]
Perhaps an option for the default plugin pack because:

- processing markdown on each frontmatter attributes slows down the loader
- IMHO, I don't expect this at all .

**Comment by xuopled** [comment]
I could be great to make this the default behavior if is not slow down much the build

**Comment by MoOx** [comment]
If we keep the same remark instance, pretty sure this won't be a problem. Anyway, this might be subject for a new plugin included in the default markdown preset, so people might skip it if not needed. Let me make a twitter poll for this https://twitter.com/Phenomic_app/status/800737752794939392

**Comment by xuopled** [comment]
I tried to handle this but when my `webpack` load the plugin I have the error `Unexpected token import` for my first import

**Comment by MoOx** [comment]
Try using es5. What phenomic version are you using?

**Comment by xuopled** [comment]
Thank you. I was my phenomic version indeed.

So in my webpack config I did 

```
phenomic: {
      plugins: [
        ...require("phenomic/lib/loader-preset-default").default,
        ...require("phenomic/lib/loader-preset-markdown").default,
        ...require("./src/loader-plugin-transform-md-head-property-to-html").default,
      ]
    },
```

And that is my plugin code : 
```
import flatten, {unflatten} from "flat"
import remark from "remark"
import slug from "remark-slug"
import autoLinkHeadings from "remark-autolink-headings"
import highlight from "remark-highlight.js"
import toc from "remark-toc"
import html from "remark-html"

function mdify(frontMatter) {
   const flattenHead = flatten(head)
   const flattenHeadMdify = flattenHead.map(prop => remark()
     .use(slug)
     .use(autoLinkHeadings, {
       content: {
         type: "text",
         value: "#",
       },
       linkProperties: {
         className: "phenomic-HeadingAnchor",
       },
     })
     .use(html, { entities: "escape" })
     .use(highlight)
     .use(toc)
     .process(text, {
       commonmark: true,
     })
     .toString()
   )

  return unflatten(flattenHeadMdify)
}

export default ({result, frontMatter}) => ({
  ...result,
  head: mdify(result.head),
})
```

But I have the error `Module build failed: TypeError: plugin is not a function` for all my markdown files. What I did wrong ?

**Comment by MoOx** [comment]
If it's for all files, it's because it happen each time the loader is executed. In your case the "plugin" is called by the loader on each file. Your plugin seems good, not sure what is wrong here.
(btw it's suboptimal for 2 reasons: a new remark instance created each time + flatten/unflatten, which should may be handled by a recursive function with a swtich on the typeof data)

**Comment by westlicht** [comment]
Hi! I'm currently writing a static website with phenomic as well and would also like to get markdown for frontmatter items. I get the same error `Module build failed: TypeError: plugin is not a function` and found that the plugins array passed to the loader plugins contains only `null` values in case I use `plugins: [ ...require("phenomic/lib/loader-preset-markdown").default,],` in my webpack config. But looking at the code in the loader plugin, the default is to do exactly the same, in which case the plugins array will contain 5 functions. Any ideas what's happening here?

**Comment by MoOx** [comment]
"plugins" section need to be in the top level webpack config for webpack 1 (that serialize query as string then unserialize, which make function=== null). 
Please read carefully this section https://phenomic.io/docs/usage/plugins/#consuming-plugins and tell me if you still have the "null" issue.

**Comment by westlicht** [comment]
Yep, this worked, thanks for the quick reply!

**Comment by xuopled** [comment]
@westlicht If you succeed, can you share your work or just tell me what is wrong my my snippet ? Thank you

**Comment by westlicht** [comment]
@xuopled I just moved the loader plugins section to the top level webpack config, as suggested by @MoOx, because I'm using webpack 1. I'm considering switching to webpack 2 beta, but for now, this should work. The plugin code you wrote did not work as is for me and I will probably rewrite it for my needs early this week. I only want MD to be applied to certain fields, still have to figure out the best way of achieving this, maybe some configuration options or some prefix embedded to the strings that require conversion. I can post the code here once I get it working properly.

**Comment by khrome83** [comment]
I like the idea of font-matter parsing to spit out the key and value for each line so you can determine how you want to process it, and not make it the same for all fields. 

Similar to how postCSS plugins work would be ideal in my honest opinion.

**Comment by MoOx** [comment]
Doable in user land.
