### ISSUE TITLE
Add localization for docs

### ISSUE THREAD

**Issue by trkw** [phenomic/phenomic#885]
Hello from Japan.
I would like to translate phenomic docs for Japanese user.
Can you help me make docs with based on `react-intl`.  e.g. https://phenomic.io/jp/

**Comment by MoOx** [comment]
I was thinking doing the same for French users :)
I am just afraid the maintenance will be difficult and we might have non english doc out of date often. But I guess maybe we can add a notice in top of each non english page about that?

Thoughts?

**Comment by trkw** [comment]
Thank you for your comment :)

I think the following functions are necessary.
- Display update date
- Link to original(English) docs

**Comment by MoOx** [comment]
I read this again https://medium.com/@thejameskyle/the-language-of-programming-7983b8f6910d#.pyicke8tv

and think we should try https://crowdin.com/ with https://github.com/thejameskyle/crowdin-sync.

What do you think about that?

**Comment by trkw** [comment]
I see.

I look at other localization platforms similar to crowdin.

> What's the best platform to localize a website?
> https://www.quora.com/Whats-the-best-platform-to-localize-a-website

There are various platforms, but it is only a paid web service...

The following is a similar web service.
- https://phraseapp.com/
- https://localizedirect.com/
- https://poeditor.com/
- http://useshuttle.com/
- https://www.textunited.com/
- https://localizejs.com/

**Comment by MoOx** [comment]
Will probably take a look to that next week, after dotJS.

**Comment by MoOx** [comment]
Will naturally come later.
