### ISSUE TITLE
Add support and/or documentation for Contentful

### ISSUE THREAD

**Issue by MoOx** [phenomic/phenomic#886]
Following https://github.com/MoOx/phenomic/issues/461#issuecomment-225906049 and https://github.com/MoOx/phenomic/issues/719#issuecomment-261757740

This might be a good starting point https://gist.github.com/ivanoats/e79ebbd711831be2536d1650890055c4 (script to grab contentful content and save it as files)

**Comment by muhajirframe** [comment]
probably @Khaledgarbaya can help with this.

**Comment by Khaledgarbaya** [comment]
Hi there,

Having a first look at this you can make a plugin that accepts content_type and some configs like a query object, something similar to the code written in the gist. 
We have few integrations with static site generators Done in JS you can check it out [here](https://github.com/contentful-labs/contentful-metalsmith) for example
I think requiring a contentType always is a good idea in the configs, this way you can have more powerful filtering.

Answering the linked issues we have [webhooks](https://www.contentful.com/developers/docs/concepts/webhooks/) feature if you want to trigger a ci each time you publish some content.

Unfortunately I don't have time now to play around with phenomic but feel free to mention me any time , I will be glad to help you.

Best,
Khaled

**Comment by xuopled** [comment]
If you are interested into this, I create a gist. Not fully functional but you can start with this: 
https://gist.github.com/xuopled/3cf222c022a675928d7c19d9ecddad0d

**Comment by MoOx** [comment]
Coming in next release of v1
