### ISSUE TITLE
Unexpected unknown pseudo-class selector ":--headings"   selector-pseudo-class-no-unknown

### ISSUE THREAD

**Issue by MoOx** [phenomic/phenomic#894]
=> https://github.com/stylelint/stylelint/issues/2146

Happen with docs and default base theme if you use styelint standard.

**Comment by MoOx** [comment]
https://github.com/stylelint/stylelint/issues/2141

**Comment by MoOx** [comment]
False positive :(

**Comment by MoOx** [comment]
https://github.com/stylelint/stylelint/pull/2147 This should fix this issue.

**Comment by khrome83** [comment]
Yeah this was the issue i reported in Gitter a few days ago. At the time no one else was seeing it.

**Comment by MoOx** [comment]
Not relevant anymore as we don't ship with stylelint now.

**Comment by khrome83** [comment]
Why the removal of stylelint?

**Comment by MoOx** [comment]
Because it's not phenomic responsibility to decide if people should use it or not. I will provide a smilar boilerplate that what's 0.x is offering (so with stylelint included), but I got to many "false alarm" about issue related to the linter (same apply for eslint) that make me spend time on instead of working on the core (and I still have not enough time to move forward with phenomic ^^)
