### ISSUE TITLE
Incompatibility with history@4.4.2

### ISSUE THREAD

**Issue by xuopled** [phenomic/phenomic#895]
I  just installed the new version of `history`:

```console
npm i history@4.4.2
```

And I get this error during my travis build:

```
Error: Cannot find module 'history/lib/createBrowserHistory'
```

I don't have problem if I rollback to `history@2.0.0`

**Comment by thangngoc89** [comment]
React-router@^3.0.0 doesnt compat with history@^4.0.0

**Comment by MoOx** [comment]
Closing as rr 3 require a lower version.
