### ISSUE TITLE
[DX] Tell people what is occupying port on `npm start`

### ISSUE THREAD

**Issue by DavidWells** [phenomic/phenomic#897]
This seems like a nice to have for DX https://github.com/gatsbyjs/gatsby/pull/579

Not super urgent though =)

**Comment by khrome83** [comment]
I have some issue where i have multiple instances of Phenomic running, or rather it didn't finish closing out or something. Maybe showing the PID as well would help. X at PID is already running on port YYYY.

**Comment by MoOx** [comment]
I thought about that too. I would like to copy CRA UX on that.

**Comment by oscar-b** [comment]
@MoOx If this is up for grabs I'll give it a shot?
