### ISSUE TITLE
Website: Add image preloader for showcase screenshots

### ISSUE THREAD

**Issue by MoOx** [phenomic/phenomic#900]
Too many image and nothing upfront. We need at least a background or something.

**Comment by gisete** [comment]
Hi, I can help you with this. Any other details you think I should know? Thanks.

**Comment by MoOx** [comment]
Hi. Thanks for offering some help. This issue should be pretty easy to handle.
Something should be added around here https://github.com/phenomic/phenomic/blob/c9d53cd46543a459c62d4ab5f14c309c102f3386/docs/components/ShowcaseList/index.js#L110-L125 to add at least one "loader" below the "large" images.
Maybe even an simple svg spinner can do the trick. We should be able to rely on our ActivityIndicator component! Should take a few minutes only!
