### ISSUE TITLE
Remove react-helmet attributes in non-clientScripts mode

### ISSUE THREAD

**Issue by gmarty** [phenomic/phenomic#901]
When generating a purely static website (`clientScripts: false` in package.json), in the resulting pages, the elements generated by react-helmet have a `data-react-helmet="true"` attribute which is not used:
```html
<meta data-react-helmet="true" name="generator" content="Phenomic 0.19.5"/>
<meta data-react-helmet="true" property="og:site_name" content="title"/>
<meta data-react-helmet="true" name="twitter:site" content="@blahblah"/>
```

This attribute should be removed from these elements.

**Comment by MoOx** [comment]
Good idea.

**Comment by hugmanrique** [comment]
Any updates on this?

**Comment by MoOx** [comment]
@hugmanrique first of all, what version of phenomic are you using? 0.x or 1.x?

>  It seems like the react-helmet Components aren't rendered when the static site generation occurs. You can check this by disabling JavaScript on any page such as phenomic.io

That's "just" a phenomic docs bad implementation of the static rendering, thanks for reporting that :)

> react-helmet team doesn't recommend static rendering on the client side

That's not a thing we were or are doing.

FYI, phenomic 1.x is not tied directly to react (only via a plugin) and react plugin is not tied to react-helmet. Things like that are now a user land problem.
So with 1.x, there is not even a "clientScripts" option, as you can handle this yourself in your Html component by just omitting the `<Script>` tag. And for the `data-react-helmet="true"` that will be up to you to render react-helmet result as string and remove this parts. I think it's should be very easy to do. I might make an example when I got some time.

**Comment by hugmanrique** [comment]
Hi, I'm using the latest 1.0.0 beta, but you're completely right, react-helmet has nothing to do with Phenomic. I just checked how you implemented it on your docs and I saw it wasn't working as expected.

I think the `Helmet.renderStatic()` method should only get called when ` process.env.PHENOMIC_ENV === "static"`.

**Comment by MoOx** [comment]
The problem is elsewhere in webpack config. Will push a fix maybe this evening or tomorrow morning, don't worry!

**Comment by MoOx** [comment]
User land problem with v1 :)
