### ISSUE TITLE
A static build outputs JSON files

### ISSUE THREAD

**Issue by gmarty** [phenomic/phenomic#902]
When generating a purely static website (`clientScripts: false` in package.json), the JSON files that are normally used to load other pages content are generated:
```
/index.html
/index.html.69cb2ef2ed73450a813a4f957c81fc86.json
```

These files are not necessary in static builds because there are not used.

**Comment by MoOx** [comment]
Indeed we should not add this files.

**Comment by MoOx** [comment]
With 1.x, there is no clientScripts options but it's very easy to just omit the script tag (since you have full control over the Html wrapping. You have a single folder in dist called "phenomic", so very easy to just remove it (every json are in this folder).
