### ISSUE TITLE
Add ability to control what elements are in the RSS feed

### ISSUE THREAD

**Issue by mjamesderocher** [phenomic/phenomic#915]
It would be useful if out of the box there was a way to change what goes into the RSS feed. For example, if you wanted to use Phenomic for a podcast, you could generate a feed with the podcast image, media source, etc.

**Comment by thangngoc89** [comment]
I think this should be in userland, Phenomic is becoming too complicated with many options to learn. If a user wants a custom behaviour, please write one, it's pretty easy. For RSS Feed, please duplicated this webpack loader plugin https://github.com/MoOx/phenomic/tree/7a242d96ba3b1dbc88a2f5abef41c2550eac5bcf/src/loader-feed-webpack-plugin

**Comment by MoOx** [comment]
I guess we could add an option on our Feed plugin, not a big deal.
Anyway the way to access API so this might change in a near future. Will revisit this. Meanwhile a custom plugin might works but it's a bit tricky since it's accessing "private" files that are not documented or part of the public API.

**Comment by bloodyowl** [comment]
Going to be fixed with #925 (plugin options)

**Comment by mjamesderocher** [comment]
I ended up making a custom version of the loader-feed-webpack-plugin that would fit my needs. https://gist.github.com/mjamesderocher/25e3551578e91b77cfb7e88a9e500d9b

**Comment by mjamesderocher** [comment]
In the process of doing it, I'm questioning if it is really a feature that even I would suggest for the default set-up. Most people probably won't compile and host their own podcast feed as I'm doing, and with the flat-file database, metadata like duration and enclosure length would have to be manually entered in the head (which is what I'm going to do) or gotten from requests to the server each time the feed is built. 

Sometime I might fine-tune my code and publish it as an actual node module, then other people could use it if they wanted.

**Comment by MoOx** [comment]
Will be part of plugin in v1.
