### ISSUE TITLE
Markdown head property type breaks layout

### ISSUE THREAD

**Issue by 0x80** [phenomic/phenomic#932]
I created some posts with a `type` property, and found that it breaks the layout. It seems that `layout` is set as `type` on the object passed to the page component. It appears to still contain the layout value when a type is used in the head, but somewhere it breaks things because the layout is not being used in page rendering.

As a side note I think it would be useful to have a warning or error when setting a layout that is not registered. Currently it silently falls back to `Page`.

**Comment by MoOx** [comment]
Indeed layout used is type || layout. Maybe this is not documented but it's like that since the beginning.
I guess we should show warnings indeed. Will revisit this for [1.0](#https://github.com/MoOx/phenomic/issues/925)

**Comment by MoOx** [comment]
Probably not relevant with v1
