### ISSUE TITLE
Error when post file name is not URL encoded

### ISSUE THREAD

**Issue by kevin940726** [phenomic/phenomic#978]
Steps to recreate the issue:
1. Setup through the official doc
2. Run `yarn start`
3. Rename `content/posts/hello-world.md` to `content/posts/hello world.md`

Result: My chrome hanged and after a long time it logged `maximum call stack size exceeded`.

The `__url` will always be the original filename but not the url encoded ones. Not sure whether the expected behavior is to prevent user from creating non-url-encoded posts or to help users to encode the filename. But definitely not cause the browser to hang 🤔 .

**Comment by MoOx** [comment]
Thanks for reporting, will try to have a look.

**Comment by MoOx** [comment]
Probably not relevant with v1.
